Week4
ggred0123/nest-study-eventory-ymkim pull request #10
Opened 2024-11-07 10:15 UTC by ggred0123

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [ v] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
새로운 eventcity relation을 만드는 작업을 했습니다.
추가 수정 x

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

2024-11-07 10:17 UTC, ggred0123 commented
질문이 몇가지 있습니다.
한 이벤트에 몇가지 도시를 받는 다는 것은 create, put,patch 등에서 도시 id 를 리스트로 받고 한번에 반영시킨다는 의미인가요 아니면 따로 이벤트를 구현하면서 도시들을 추가할 수 있게 하는 것인가요?

2024-11-07 10:38 UTC, ggred0123 commented
eventjoin 같은거랑 다르게 eventcity는 원래 event에서 끌어올게 없다고 해야하나..? 그래서 원래 eventdata나 createeventdata를 변경하기에는 반환경이 eventdto로 정해져 있어서 여기까지는 바꾸면 안될것 같고.. 하는 문제 들이 있습니다.

2024-11-07 11:34 UTC, worjs commented
@ggred0123 
엄 우선 지금 github action이 failure가 떴네요. 에러가 있어서 서버 실행이 안되는 것 같습니다. 먼저 그걸 해결하고 다시 리뷰 요청해주시면 좋을 것 같네요!

그리고 첫번째 질문은, 맞습니다. 이제 input으로 cityId가 아니라 cityIds를 받아야 한다는 의미입니다! create put, patch모두 영향이 있을 것 같아요. 그리고 get도 달라지겠죠?  cityIds를 내려주어야 하니까요.

두번째 질문에 대해서는, 사실 명확히 이해가 되지는 않는데요, 

> eventjoin 같은거랑 다르게 eventcity는 원래 event에서 끌어올게 없다고 해야하나..?

요게 migration에서 데이터 이전에 관련한 의미로 말해주신거면... 끌어올게 있죠? 원래 event 안에는 cityId가 하나 있었는데, 이제 이걸 복수로 허용했으니 eventCity 테이블로 가야할겁니다.

반환하는 EventDto의 모습도 바뀌어야 합니다. event는 이제 city를 여러개 가지고 있으니 여러개 내려주어야겠죠?

2024-11-07 14:38 UTC, ggred0123 commented
약간 에러를 잡기가 힘들다고 해야하나..? event 데이터 안에 cityId를 정의해 놓지 않고 generate를 했다 보니 
![image](https://github.com/user-attachments/assets/4e781ddb-8b19-4d04-a0de-d8100056a7d1)
이 그림 같은 곳에서
![image](https://github.com/user-attachments/assets/4853072b-8eed-4b72-a155-2d337a40b629)
cityIds는 index.d.ts에 정의되어 있지 않아서 쓸 수 없다고 되어 있는데 이걸 도대체 어떻게 해야할 지 모르겠습니다..

2024-11-07 14:40 UTC, ggred0123 commented
아 그리고 끌어올게 없다고 말한 것의 의미는 단순히 eventdata와 createeventdata에서 cityid 만 단순 삭제 했을 경우 data.eventid, data.cityid가 없으니 
createevent 내에서 eventcity 안의 create 안에 들어갈 항목이 없다는 얘기였습니다! @worjs

2024-11-07 14:47 UTC, worjs commented
이제 cityId는 user 테이블에는 없는 셈이니까요, 이제 user 테이블에서는 못구합니다.
대신 eventCategory 테이블로 옮겼으니까, 그쪽에 create하고 그쪽에서 select하면 됩니다.

이런 경우에는 라이브러리 동작을 이해를 못한 상황이기도 하니까요, docs를 찾아가보는게 좋습니다
https://www.prisma.io/docs/orm/prisma-client/queries/relation-queries
요 문서에서 필요로하시는 답이 있을 듯 하니 찾아보세요!

객체지향 관련한 논의들을 하다보면, 변하기 쉬운 코드와 변하지 않는 코드를 잘 구분해야 한다는 말이 있는데, 우리 서버에서는 DB와 관련된 코드들, http와 관련된 코드들(dto, payload, query ...)등이 가장 핵심 로직에서 멀고 변하기 쉬운 코드입니다. 반대로 service의 코드들이 변화가 적은 핵심 로직들이 담긴 코드가 됩니다.

아무튼 type, dto들은 언제든지 바뀔 수 있다고 생각하고 접근하시면 좋을듯!

2024-11-07 15:00 UTC, ggred0123 commented
명심하겠습니다!

2024-11-08 01:26 UTC, worjs requested changes
방향성은 거의 맞는 것 같습니다~~ 화이팅!

2024-11-08 01:26 UTC, worjs commented on src/event/payload/create-event.payload.ts
> +
오예 each: true 옵션 맞아요 굿굿

2024-11-08 01:26 UTC, worjs commented on src/event/event.repository.ts
> +          })),
어라 cityIds가 undefined 가능성이 있나요? `cityIds?` 이렇게 안해도 될거같은데

2024-11-08 01:26 UTC, worjs commented on src/event/event.repository.ts
> +        },
update의 경우에는 undefined => 업데이트 안하겠다.
null, "", [] 등 => 해당 값으로 업데이트하겠다.
라는 의미가 됩니다.
data.cityIds ?? [] 로 해버리면 undefined로 요청했는데 cityId 정보가 모두 날아갈 것 같아요

2024-11-08 01:26 UTC, worjs commented on src/event/event.repository.ts
> +      }),
transaction api를 사용한 것도 좋은 접근이지만, relation query를 이용해서 event 지울 때 한방에 지울 수 있을거예요.

2024-11-08 01:26 UTC, worjs commented on src/event/event.service.ts
> +    const city = await this.eventRepository.getCityById(payload.cityIds[0]);
음 cityId 전부가 input이니까 전부 확인해줄 필요가 있습니다.

2024-11-08 01:26 UTC, worjs commented on src/event/event.service.ts
> +          throw new NotFoundException('city가 존재하지 않습니다.');
맞아요! cityIds 전부를 확인해봐야 하는데, 이렇게 하나씩 DB에서 확인해오면 만약에 cityIds가 100개짜리면 왕복 네트워크 비용이 200회가 되어서 느려지게 됩니다.

RDB에서 Select Query를 칠때 where 절에 넣을 수 있는 조건중에 IN이라는 조건절이 있습니다.
prisma에서도 그게 구현되어 있으니, cityIds의 유효성을 검사하는데 DB쿼리 한방만 사용하는 방향으로 고쳐보면 좋을 것 같네요!

2024-11-08 01:26 UTC, worjs commented on src/event/event.repository.ts
> +import { create } from 'lodash';
안쓰는 import는 보일때마다 지우기 !

2024-11-08 03:52 UTC, ggred0123 commented on src/event/event.repository.ts
> +          })),
네 그냥 map 했더니 undefined 일 수 있습니다로 떴어서 그렇게 바꿔놓긴 했습니다!

2024-11-08 05:53 UTC, worjs commented on src/event/event.repository.ts
> +          })),
진짜요? 아닐거같은데... 다시 지워보셨나요

2024-11-08 07:04 UTC, ggred0123 commented on src/event/event.repository.ts
> +          })),
다시 살펴보겠습니다!

2024-11-08 07:15 UTC, ggred0123 commented on src/event/event.repository.ts
> +      }),
아 이게 relation으로 쓰려면 update를 사용해서 먼저 지워야 하는건가요?

2024-11-08 07:34 UTC, ggred0123 commented on src/event/event.service.ts
> +          throw new NotFoundException('city가 존재하지 않습니다.');
레포지토리에 in을 사용하는 함수 하나를 구현해보았습니다!

2024-11-08 07:34 UTC, ggred0123 commented on src/event/event.repository.ts
> +import { create } from 'lodash';
넵 알겠습니다!

2024-11-08 07:34 UTC, ggred0123 commented on src/event/event.service.ts
> +    const city = await this.eventRepository.getCityById(payload.cityIds[0]);
넵 확인했습니다!

2024-11-08 07:35 UTC, ggred0123 commented on src/event/event.repository.ts
> +        },
그냥 한번에 update하는 방식으로 해보겠습니다!

2024-11-08 14:58 UTC, worjs requested changes
코멘트 추가로 달아드렸습니다!

다음번에는 오른쪽 위에서 저 리뷰 re-request 해주시면 더 좋을거같아용

2024-11-08 14:58 UTC, worjs commented on src/event/event.repository.ts
> +  }
함수 이름이 단순히 id check이라는 의미보다는 더 구체적이면 좋겠습니다!
cityIds의 무엇을 check하는지 생각해보시면 좋을듯

2024-11-08 14:58 UTC, worjs commented on src/event/event.repository.ts
> +          })),
이거 실제로 되는지 확인해보셔야 할거같아요ㅋㅋㅋㅋ

2024-11-08 14:58 UTC, worjs commented on src/event/event.repository.ts
> +      }),
delete 메소드 하나로 연결해서 지울 수 있을거예요

2024-11-08 14:58 UTC, worjs commented on src/event/event.service.ts
>        throw new NotFoundException('city가 존재하지 않습니다.');
요거는 실수같네요ㅋㅋㅋ

2024-11-08 14:58 UTC, worjs commented on src/event/event.service.ts
>        }
변수 이름 쬐끔만 더 고민해서 지어주세요!!

2024-11-08 14:58 UTC, worjs commented on src/event/dto/event.dto.ts
> -
어라 없어지기만 하나요??

2024-11-08 16:06 UTC, ggred0123 commented on src/event/dto/event.dto.ts
> -
아닌.. 가요? datatype 에서도 create,update 부분만 바꾸고 eventData는 그대로 뒀는데..
처음에 dto에 cityIds를 넣었다가 eventData를 바꾸라고 빨간줄이 떠서 바꿨더니 repository에서 손쓰기 힘든 에러가 났어서.. 
넣는 것과 아래에서 from에 eventdto에 오류가 안나기 위해서 일단 optional 조건?(아닌 것 같지만).. 을 붙여서 넣어보겠습니다..ㅜ

2024-11-08 16:06 UTC, ggred0123 commented on src/event/event.service.ts
>        }
넵! 확인했습니다!

2024-11-08 16:07 UTC, ggred0123 commented on src/event/event.service.ts
>        throw new NotFoundException('city가 존재하지 않습니다.');
아고 저기 또 있었군요 ㅜㅜ

2024-11-08 16:07 UTC, ggred0123 commented on src/event/event.repository.ts
> +  }
넵! 유효성 검증한다는 의미로 validity를 넣겠습니다

2024-11-08 16:54 UTC, ggred0123 commented on src/event/event.repository.ts
> +          })),
음.. update 부분을 어떻게 해야할지 모르겠네요.. 삭제를 먼저 하면 다 날아가버리고.. 그냥 한번에 update되거나 cityIds가 undefined일 때는 삭제를 안하는 로직이 들어가면 좋을 것 같은데.. 자고 일어나서 좀 더 고민해보겠습니다!

2024-11-09 08:06 UTC, worjs commented on src/event/event.repository.ts
> +  }
오 훨 좋은 이름이네요
근데 validity의 v가 대문자면 좋을듯

2024-11-09 08:06 UTC, worjs commented on src/event/event.repository.ts
>    }
헐 이거 제가 잘못 알고 있었네요.. 죄송해요
저는 delete 함수 한방으로 다 지울 수 있을줄 알았음 ,,,,,,,, 죄송해요....
그렇게 되면 무조건 2개 이상의 함수를 사용해야하니 transaction으로 묶어서 처리해야겠군요...

아 그리고 추가로 함수 이름은 그냥 deleteEvent면 충분하지 않을까 싶습니다.
원래 event에 완전 종속된 정보들인데 관계형 데이터 구조여서 어쩔 수 없이 테이블이 분리된거니까요.

2024-11-09 08:06 UTC, worjs commented on src/event/event.service.ts
> +      throw new NotFoundException('존재하지 않는 city가 포함되어 있습니다.');
camelCase!

2024-11-09 08:06 UTC, worjs commented on src/event/dto/event.dto.ts
> -
이쯤에서 고민을 한번 해볼 때가 된 것 같습니다.

첫시간에 각 레이어들의 역할에 대해 언급한 적이 있었는데요, 

repository는 받은 정보(데이터)로 DB에 쿼리를 날리고 받아온 데이터를 리턴합니다. 해당 정보를 가지고 어떤 로직을 수행해서 다시 repository에 요청을 보내거나 이런저런 비즈니스 로직을 수행하는 곳은 Service. 최종 완성된 데이터를 받아서 응답 타입에 맞게 포맷하는 곳은 Dto 의 static 메소드에서 진행하기로 했었습니다.

그럼 Type은 뭐냐?
Repository는 DB에서 가져온 SQL 응답 데이터를 JS 형태로 재구성해서 타입을 만들어 줍니다. 근데 이 타입은 내가 select를 어떤 것들을 골랐냐에 따라서 바뀌도록 설계된 복잡한 타입이기 때문에 읽기가 쉽지 않습니다. 그래서 이 타입을 쉽게 주고받기 위해 우리 프로젝트에서 type이라는 계층을 도입한거라고 보시면 됩니다. repository에서 응답으로 넘겨주는 데이터를 내가 type이라는 형태로 정의해서 service에 돌려주는 것이죠. 즉, type은 repository에 더 의존하자고 정한겁니다.

그럼 여기서 우리의 요구사항은 DTO가 바뀐다, cityIds로 내려줘야 합니다. payload도 cityIds로 받았으니 똑같이 돌려주는게 좋겠죠. 그러면 EventType과 EventDto의 형태가 다른 상황이 됩니다. 이런 상황을 핸들하려고 "포장"이라는 말을 써가며 static from 메소드를 도입하게 된 것이라고 보시면 됩니다. 지금까지는 static from 메소드에서는 말그대로 꺼내서 그대로 놓기만 해서 엄청 형식적인 곳으로 느껴졌을 수도 있는데요, data type과 dto의 차이를 메꿔주는 곳이고 여기서 형태를 응답 형태(DTO)에 맞게 새로 포장해주시면 되겠습니다.

어찌되었건 이 방식들이 정답은 아닙니다. 제가 정한거구요, 고민해보시다가 별로라고 느껴지시면 마음대로 하셔도 됩니다. 대신 그때는 나름의 근거를 제안해주시면 좋은 토론 기회가 되겠죠!

2024-11-09 08:14 UTC, worjs requested changes
잘 따라오고 계십니다..! 지금까지보다 어려운 작업이 맞으니 힘내서 가봅시다...!!

2024-11-09 08:14 UTC, worjs commented on src/event/event.repository.ts
> +        },
이 부분이 많이 어려울 수 있습니다.
먼저 작업이 어떻게 이루어지길 바라는지 먼저 고민해 보세요.

현재 cityIds는 없으면 => 업데이트 안함
있으면 기존 cityIds는 전부 날리고 새로운 cityIds로 대체

인 상황이죠.

그럼 구현을 할때, **"먼저"** cityIds의 존재 여부를 가지고 eventCity에 값을 넣을지 말지를 가르는 코드가 들어가야 할테고, 그 다음에 존재하는 상황이라면, 2가지 작업을 해야할겁니다. 모든 city들을 지우고, 새로운 city들을 집어넣도록요.

위에까지 고려했다면 이제 2가지 중에 한 가지 방법으로 해야 합니다.
1. update 메소드 한방으로 어떻게든 해결하기 => 가능하다면 이게 best
2. 도저히 모르겠다면 여러 메소드로 쪼개서 날리기. 대신 transaction으로 묶어야 합니다.

힌트를 드리면 삼항 연산자가 도움이 될 것 같습니다.

2024-11-09 10:25 UTC, ggred0123 commented on src/event/event.repository.ts
> +        },
...(data.cityIds !== undefined && {
        eventCity: {
          updateMany: {
            where: {
              eventId: eventId,
            },
            data: data.cityIds.map((cityId) => ({
              cityId: cityId,
            })),
          },
        },
      }),
      이런식으로 해봤었는데 안돼서(invalid value) delete create 로 구현했습니다!

2024-11-09 10:28 UTC, ggred0123 commented on src/event/event.repository.ts
> +        },
그리고 cityIds 가 undefined 인지를 확인하는 코드를 if 문으로 짜려고 했는데 왜인지 오류가 계속 나서 인터넷 검색 후 병합 연산자로 구현해보았습니다

2024-11-09 10:28 UTC, ggred0123 commented on src/event/event.service.ts
> +      throw new NotFoundException('존재하지 않는 city가 포함되어 있습니다.');
확인했습니다!

2024-11-09 10:43 UTC, ggred0123 commented on src/event/event.repository.ts
>    }
넵 확인했습니다!

2024-11-10 05:54 UTC, worjs requested changes
진짜찐찐막!!

2024-11-10 05:54 UTC, worjs commented on src/event/event.repository.ts
> +        }),
오 드디어 맞네요

제가 생각한 답안을 적어드리면
```
eventCity : data.cityIds ? {
            deleteMany: {
              eventId: eventId,
            },
            create: data.cityIds.map((cityId) => ({
              cityId: cityId,
            })),
          } : undefined
```

2024-11-10 05:54 UTC, worjs commented on src/event/event.repository.ts
> +        }),
이런 느낌이었는데 영민님이 한 방법도 괜찮은거같아요

2024-11-10 05:54 UTC, worjs commented on src/event/event.service.ts
> +      throw new NotFoundException('존재하지 않는 city가 포함되어 있습니다.');
이정도면 괜찮은데

제가 생각한 답은 isCityIdsValid 였습니다.
T/F로 오는 경우는 저는 is로 시작 많이 하거든요

2024-11-10 05:54 UTC, worjs commented on src/event/type/event-data.type.ts
>    maxPeople: number;
음 조금 설명이 추상적이었나 생각이 드네요.

data type은 repository의 반환형에 의존한다. 즉 repsitory에서 prisma가 뱉어내는 타입을 그대로 EventData 타입으로 만들주셨으면 좋겠다는 의미였습니다.

그래서 조회할 때도 eventCity들을 한번에 같이 조회하구요
```
await this.prisma.event.findMany({
      where: {
        hostId: 1,
      },
      select: {
        id: true,
        hostId: true,
        title: true,
        description: true,
        categoryId: true,
        eventCity: {
          select: {
            id: true,
            name: true,
          },
        },
        startTime: true,
        endTime: true,
        maxPeople: true,
      },
    });
```
위를 조회해서 나온 데이터의 타입은 기존과 달라지겠죠. 우린 select문을 곧바로 리턴하고 있으니까 EventData라는 타입을 바꿔줘야 타입이 맞게 됩니다. 직접 결과를 콘솔로 찍어보고 판단하셔도 되고, 응답 결과를 잠깐 변수로 받은 다음에 마우스를 올려보면 응답 타입이 나오니까 그걸 참조해도 됩니다.

그러면 EventData는 아래처럼 바뀝니다.
```
export type EventData = {
  id: string;
  hostId: string;
  title: string;
  description: string;
  categoryId: number;
  startTime: Date;
  endTime: Date;
  maxPeople: number;
  eventCity: {
     id: number;
     name: string;
  }[];
};
```

보기 안좋다 생각이 들면
event city만 따로 새로운 타입으로 할수도 있죠

```
export type CityData = {
  id: number;
  name: string;
};

export type EventData = {
  id: string;
  hostId: string;
  title: string;
  description: string;
  categoryId: number;
  startTime: Date;
  endTime: Date;
  maxPeople: number;
  eventCity: CityData[];
};
```

그럼 이제 이렇게 받아온 데이터를 static 메소드에서 포장하는겁니다.
나머지는 다 똑같을텐데 cityIds 부분만 다르죠.
`cityIds : data.eventCity.map((city) => city.id);`
이렇게 넣어주면 되겟죠?

2024-11-10 05:54 UTC, worjs commented on src/event/query/event.query.ts
> -  cityId?: number;
얘도 없어지면 안됩니다~~

2024-11-10 05:54 UTC, worjs commented on src/event/query/event.query.ts
> -  cityId?: number;
모임의 지역을 복수로 설정할 수 있게 했다고 해서 xx지역의 모임을 조회하는 기능 자체가 사라지는건 안됩니다ㅎㅎㅎ

2024-11-10 08:58 UTC, ggred0123 commented on src/event/event.repository.ts
> +        }),
넵 감사합니다!

2024-11-10 08:58 UTC, ggred0123 commented on src/event/event.service.ts
> +      throw new NotFoundException('존재하지 않는 city가 포함되어 있습니다.');
아 그렇군요! 감사합니다!

2024-11-10 08:59 UTC, ggred0123 commented on src/event/type/event-data.type.ts
>    maxPeople: number;
아아 저는 data type을 절대 전드리지 말고 차이를 dto의 from에서 메꿔라!하는걸로 잘못 이해를 해서 굉장히 엄청난 짓을 했었군요..

2024-11-10 08:59 UTC, ggred0123 commented on src/event/query/event.query.ts
> -  cityId?: number;
아아 그렇군요! 감사합니다!

2024-11-10 09:02 UTC, ggred0123 commented
그리고 혹시 erdiagram은 사이트에서 
https://dbdiagram.io/d/goody-erdiagram-673031f1e9daa85acae7ff4b
이런식으로 짜는 것 맞나요? manytomany 따로 구현하는 것까지 해봤는데..

2024-11-10 09:27 UTC, worjs commented on src/event/type/event-data.type.ts
>    maxPeople: number;
이해합니다! 사실 이 내용들이 객체지향 관련한 이해가 없으면 뭐하는짓인가.. 싶거든요... 제가 설명을 더 잘해드렸어야 했을 것 같아용 호호

2024-11-10 09:37 UTC, worjs approved these changes
와 짝짝짝 고생많으셨습니다!!!

단순히 하나짜리였는데 배열로 바뀐 것 만으로도 꽤 복잡해졌죠?
나중에는 값 배열이 아니라 객체 배열로도 데이터 받아서 처리할 일도 생기고 2중 3중 중첩된 DTO를 내려줄 일도 생기고 그럴 수 있어요. 그때도 최대한 각 레이어의 역할을 고민하면서 신중하게 코드를 위치시킬 수 있으면 좋겠습니다. 고생하셨어요!

2024-11-10 09:37 UTC, worjs commented on src/event/event.repository.ts
> +        ...(query.cityId && { eventCity: { some: { cityId: query.cityId } } }),
굿굿굿굿

2024-11-10 09:37 UTC, worjs commented on src/event/event.service.ts
> +    );
필요 없어진 것 같죠?

2024-11-10 09:37 UTC, worjs commented on src/event/event.service.ts
> +    );
이제 지워버릴 코드지만 그냥 코멘트를 하나 드리자면

만약에 저 map의 개수가 1000개 10000개면 어떻게 될까요?
DB를 향해 동시에 10000개의 요청이 날아가게 됩니다.

사용자가 많아져서 동시에 이 api를 치는 사람이 10명이면 100000개의 DB 요청이, 100명이면 1,000,000개의 DB 요청이 나오게 됩니다.

결론은 위와 같은 조회를 하고싶으면 in절을 이용하시길!

2024-11-10 09:37 UTC, worjs commented on src/event/dto/event.dto.ts
>    }
????

2024-11-10 09:37 UTC, worjs commented on src/event/dto/event.dto.ts
>    }
아 흔적이군요
cityIds 저거 안쓰는 매개변수 된거죠?

2024-11-10 09:38 UTC, ggred0123 commented on src/event/type/event-data.type.ts
>    maxPeople: number;
아뇨 전 고생하면서 배운다는 주의라.. 이 부분이 기억에 깊게 남을 것 같아 좋습니다!

2024-11-10 10:03 UTC, worjs commented
ERD는 손으로(?) 그리셔도 되고 자유롭게 하시면 됩니다.
어쨋든 담겨야 하는 정보들이 잘 담기면 된다고 생각해요.

2024-11-10 11:26 UTC, ggred0123 commented on src/event/dto/event.dto.ts
>    }
네네 맞습니다 지우는걸 깜빡했네요ㅠ

2024-11-10 11:48 UTC, ggred0123 commented on src/event/event.service.ts
> +    );
넵! cityids 체크할 때랑 비슷한 맥락이네요!

2024-11-10 11:52 UTC, merged