Week5 user get 구현
ggred0123/nest-study-eventory-ymkim pull request #15
Opened 2024-11-12 09:26 UTC by ggred0123

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [v ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

user db 에서 get api 구현하는 작업 진행하였습니다. user category 없는 제 데이터 베이스에서 진행하였습니다.

2024-11-12 16:18 UTC, worjs requested changes
엄청 빠르시네요 ㄷㄷㄷ

2024-11-12 16:18 UTC, worjs commented on src/event/event.repository.ts
>          where: {
어라??

2024-11-12 16:18 UTC, worjs commented on src/event/event.service.ts
> +      throw new NotFoundException('존재하지 않는 user입니다.');
요건 필요 없습니다.
JwtStrategy 클래스의 validate 함수에서, 복호화되서 꺼낸 userId를 가지고 실제 DB에 조회해서 가져온게 CurrentUser 데코레이터로 가져온 user거든요.

2024-11-12 16:18 UTC, worjs commented on src/event/event.service.ts
>      await this.eventRepository.outEvent(eventId, userId);
어라 얘도 여기 있으면 될까요?

2024-11-12 16:18 UTC, worjs commented on src/event/event.service.ts
> +    }
개인적으론 권한 확인보단 host가 맞는지 확인한다는 맥락이 더 낫지 않을까 싶긴 해요
그러고 이건 수업때 이야기한게 아니긴 한데, "인가" 즉, 권한에 대한 에러 리턴은 403 Forbidden을 또 많이 씁니다ㅋㅋ

2024-11-12 16:18 UTC, worjs commented on src/user/dto/user.dto.ts
> +
null 가능인 경우 nullable: true라는 옵션 넣어주시면 null 여부가 표현이 됩니다.

2024-11-12 16:18 UTC, worjs commented on src/user/payload/patch-update-user.payload.ts
> +  email?: string | null;
무려 IsEmail이라는 데코레이터도 있다는거

2024-11-12 16:18 UTC, worjs commented on src/user/payload/patch-update-user.payload.ts
> +  birthday?: Date | null;
얘도 null 가능이니까 nullable:true!

2024-11-12 16:18 UTC, worjs commented on src/user/user.service.ts
> +  }
살짝 애매합니다 함수이름ㅋㅋㅋㅋ
그리고 저는 이렇게 단순한? 코드라면 굳이 빼야하나 하는 생각이 들어요,
userId랑 UserBaseInfo type을 인자로 줘서 옳은유저인지 확인한다 라는 함수인데, 그냥 보면 뭐가 옳은 유저인지 확인하는거지? 라는 생각이 들 것 같습니다.

2024-11-12 16:18 UTC, worjs commented on src/user/user.service.ts
> +  }
보너스로 첨언하자면
async는 내부에 비동기 동작이 있는 경우에 붙이는 키워드입니다.
async를 붙이면 그 내부에서 await으로 비동기 함수들을 조작할 수 있구요, 리턴 타입이 Promise가 됩니다.

근데 이 함수는 단순비교 if문만 있기 때문에 비동기 함수라고 할 수는 없죠.

2024-11-12 16:18 UTC, worjs commented on src/user/user.service.ts
> +    }
email은 id같은거라서 유일한지 확인 필수!

2024-11-12 16:18 UTC, worjs commented on src/user/user.service.ts
> +    }
놀랍게도 이 두 값은 null이 될 수 있기 때문에 이 처리 해주면 안됩니다.
event 모듈에는 그런 값이 없었어요

2024-11-12 16:18 UTC, worjs commented on src/event/event.controller.ts
> +    return this.eventService.outEvent(eventId, payload.userId, user);
모임에 참가하고 탈퇴하는건 본인만 수행할 수 있어야 한다고 생각해요.
그러면 굳이 payload에서 값을 받아올 필요가 있을까요ㅎㅎㅎ

2024-11-12 16:18 UTC, worjs commented on src/event/event.controller.ts
>    @Get(':eventId')
요기도! event를 생성하는 사람이 host니까 이 요청을 보낸사람이 자연스레 호스트라는 결론이 나오겠죠?

2024-11-13 04:23 UTC, ggred0123 commented on src/event/event.repository.ts
>          where: {
음..? 서비스 레포지토리 급하게 바꾸다가 음..

2024-11-13 04:29 UTC, ggred0123 commented on src/event/event.service.ts
> +      throw new NotFoundException('존재하지 않는 user입니다.');
확인했습니다!

2024-11-13 04:29 UTC, ggred0123 commented on src/user/dto/user.dto.ts
> +
넵 확인했습니다!

2024-11-13 07:56 UTC, ggred0123 commented on src/event/event.service.ts
> +    }
확인했습니다!

2024-11-13 07:56 UTC, ggred0123 commented on src/user/dto/user.dto.ts
> +
아 또 까먹었네요ㅜ

2024-11-13 07:57 UTC, ggred0123 commented on src/user/payload/patch-update-user.payload.ts
> +  email?: string | null;
오우.. 그랬군요..

2024-11-13 07:57 UTC, ggred0123 commented on src/user/payload/patch-update-user.payload.ts
> +  birthday?: Date | null;
넵!

2024-11-13 07:57 UTC, ggred0123 commented on src/user/user.service.ts
> +  }
그냥 넣어주겠습니다!

2024-11-13 07:59 UTC, ggred0123 commented on src/user/user.service.ts
> +    }
아아 review에 description이 이랬었는데!

2024-11-13 07:59 UTC, ggred0123 commented on src/event/event.controller.ts
> +    return this.eventService.outEvent(eventId, payload.userId, user);
아 맞네요.. 어차피 user로 하면 되는구나

2024-11-13 08:01 UTC, ggred0123 commented on src/event/event.service.ts
>      await this.eventRepository.outEvent(eventId, userId);
자기만 나갈 수 있게 체크해야하는거.. 아닌가요?

2024-11-13 08:12 UTC, ggred0123 commented on src/event/event.controller.ts
>    @Get(':eventId')
네.. 
제가 이해한게 맞다면 
그냥 만드는 과정 자체에는 요청을 보낸 사람이 그냥 호스트가 되는거니까 어떠한 인증도 필요가 없다.. 맞나요?

2024-11-13 08:16 UTC, ggred0123 commented on src/user/user.service.ts
> +    }
넵! 수정해보겠습니다!

2024-11-13 08:17 UTC, ggred0123 commented on src/user/user.service.ts
> +  }
아아 async await에 대한 이해가 조금 부족했던 것 같습니다!

2024-11-13 10:10 UTC, worjs commented on src/user/user.service.ts
> +  }
네네 요건 어려울 수 있어요
사실 무조건 await을 붙여야하는건 아니고,,, 결과를 받아보거나 비동기 처리의 에러를 핸들링하지 않아도 되는 상황에서는 성능을 위해 await을 빼기도 합니다.

2024-11-13 10:12 UTC, worjs commented on src/event/event.controller.ts
>    @Get(':eventId')
어 반대입니다
요청을 보낸 사람이 호스트가 되고, 요청을 보낸사람 정보는 인증 과정을 거치고 나온 정보라는거죠.
payload에 hostId를 담을 필요가 없다는 뜻!

2024-11-13 10:12 UTC, worjs commented on src/event/event.service.ts
>      await this.eventRepository.outEvent(eventId, userId);
근데 저 코드는 event의 hostID가 userId랑 같은건지 확인하는 코드더라구요

2024-11-13 10:13 UTC, worjs commented on src/event/event.service.ts
>      await this.eventRepository.outEvent(eventId, userId);
애매한 이름을 지으면 안되는이유 ㅎㅎㅎ ,,,,

2024-11-13 10:16 UTC, worjs commented on src/event/event.controller.ts
>    @Get(':eventId')
아 그리고 인증도 필요 없죠
이미 인증 과정에서 DB에 있는지 없는지 조회도 하고 UserData를 가져온거거든요

토큰에는 userId만 담겨져 있었고, 복호화해서 userId를 꺼낸 다음에 DB에서 조회를 해서 데이터를 만든겁니다.
그거는 JwtStrategy 가보면 볼 수 있어요

2024-11-13 12:43 UTC, ggred0123 commented on src/event/event.service.ts
>      await this.eventRepository.outEvent(eventId, userId);
헉 진짜 그러네요.. 그리고 애초에 outEvent 인자로 들어가는게 user.id니깐..

2024-11-13 12:48 UTC, ggred0123 commented on src/event/event.controller.ts
>    @Get(':eventId')
음.. 일단 제가 이해한대로 service와 payload 를 바꿔보겠습니다!

2024-11-13 13:31 UTC, worjs commented on src/event/event.service.ts
> +
함수이름 너무 길어서 이상하다 싶으시겠지만, 의미 전달만 똑바로 된다하면 짧은이름보단 긴 이름이 무조건 좋아요. 100자 넘어가는거만 아니면 ㅋㅋ

2024-11-14 03:42 UTC, ggred0123 commented on src/event/event.service.ts
> +
아 ㅋㅋㅋㅋ
알겠습니다!

2024-11-14 04:04 UTC, closed without merging