승급전 pr
ggred0123/nest-study-eventory-ymkim pull request #17
Opened 2024-11-14 13:58 UTC by ggred0123

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [v ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
클럽이라는 데이터 베이스를 만들고 관리하고, 클럽 내에 모임을 만드는 기능을 만들었습니다.
처음에는 EventClub이라는 것을 만들고 모든걸 따로 처리하는 로직으로 만들었다가 생각을 해보니 clubid 를 nullable 로 처리하는 로직을 event 내에 구현하면 그냥 기존 event만으로 구현해도 아무런 상관이 없다는 것을 발견하고 event 내에 clubId? : number 를 추가하여 구현해보았습니다.
아마 지적받을 것 같지만 club waiting list에서 approve 와 reject를 받을 때 string으로 직접 approve 와 reject를 받도록 설계하였는데 이 부분을 어떻게 바꾸면 좋을지 아직은 잘 모르겠습니다..(0,1)을 받을 수도 없고.. 음..

2024-11-14 19:00 UTC, worjs requested changes
1. 변수는 camelCase
2. 에러 메세지
3. EventModule에 Club 관련 처리 추가
4. 외에도 많은데... 많은 것 같아요....

한방에 우와아아악 해서 주셨는데, 너무 많아서 리뷰하기가 어렵네요ㅠ
코드리뷰라는게 실제로 배포하기 전에 담당자와 리뷰어가 같이 코드를 점검하고 책임을 나누는 과정인데, 이렇게 범위가 커버리면 둘이 열심히 보더라도 버그나 예외를 놓친 채로 배포되어서 나중에 더 큰 문제로 돌아올 수 있어요.

PR의 크기는 에러가 안나는 하나의 기능 단위로 가능한 최소한의 크기로, 저는 되도록이면 코드 200줄 안쪽으로 내려고 하는 편입니다. 그래야 보는 사람도 명확하게 어떤 작업인지 인지하고 리뷰를 할 수 있거든요. 만약에 그게 어려우시다면 아직 본인이 해야 할 작업에 대해 명확하게 고민하지 않고 일단 코드부터 적었기 때문에 그럴 수 있습니다.

귀찮더라도 가능하면 기능별로 여러개의 PR로 나누어서 올려주시거나, 제가 이해할 수 있게 작업내용과 고려사항들을 별도로 문서화해서 넘겨주시는게 좋을 것 같습니다ㅎㅎ,,

아 그리고 혹시라도 명확하지 않거나 이런 경우에는 어떻게 하지? 라는 생각이 드신게 있다면 언제든지 질문해주세요! 일단 개발 X, 무조건 뭐든지 명확하게 하고 개발해야합니다!

2024-11-14 19:00 UTC, worjs commented on src/club/club.controller.ts
> +@Controller('Clubs')
`clubs`!

2024-11-14 19:00 UTC, worjs commented on src/club/club.controller.ts
> +  @Get(':ClubId')
요기도 다 clubId로 해서 camelCase로 하는게 나을듯

2024-11-14 19:00 UTC, worjs commented on src/club/club.controller.ts
> +  }
?? 같은 URL이네요?

2024-11-14 19:00 UTC, worjs commented on src/club/club.repository.ts
> +        status: 'PENDING',
Enum이니까 문자열로 직접 관리하기보다는 WatingStatus.PENDING
이런식으로 prisma에서 만들어준 타입이 있을거예요

2024-11-14 19:00 UTC, worjs commented on src/club/club.repository.ts
> +  }
여기도 회원탈퇴한 사람이 있을지도!

2024-11-14 19:00 UTC, worjs commented on src/club/club.service.ts
> +  }
leadID 검증?

2024-11-14 19:00 UTC, worjs commented on src/club/club.service.ts
> +    }
에러메세지 확인!

2024-11-14 19:00 UTC, worjs commented on src/club/club.service.ts
> +    }
가입 신청은 해도 되지 않을까요? 진짜 가입하는건 아니니까요!

2024-11-14 19:00 UTC, worjs commented on src/club/club.service.ts
> +  }
탈퇴가 너무 쉬운데요? 혹시 좀 더 고려해야할 상황들이 있지 않을까요?

2024-11-14 19:00 UTC, worjs commented on src/club/club.service.ts
> +  }
decision보단 approve라는 단어가 더 좋지 않을까 생각합니다!
그리고 reject와 approve를 단순히 string으로 관리하는 것보다는 enum이나 boolean으로 관리하는게 더 명확하다고 생각합니다.

2024-11-14 19:00 UTC, worjs commented on src/club/club.service.ts
> +  }
3번째 else문이 나올 필요도 없어질듯!

2024-11-14 19:00 UTC, worjs commented on src/club/club.service.ts
> +  ): Promise<ClubDto> {
lead 이전을 여기서 하지 않을 이유가 있나요??

2024-11-14 19:00 UTC, worjs commented on src/club/club.service.ts
> +    await this.checkLeadPermissionOfClub(clubId, user.id);
DB에 같은 요청을 결국 2번 보내게 되는 것 같은데, 한번으로 줄이는게 좋아보여요

2024-11-14 19:00 UTC, worjs commented on src/club/club.repository.ts
> +  }
이렇게 지우면 끝?
만약에 club 전용 event들이 있었다면 어떻게 될까요?

2024-11-14 19:00 UTC, worjs commented on src/event/event.service.ts
> +  ) {}
이거 아마 에러날거같은데 그쵸
ClubRepository 가져오지말고 전부 EventRepository에 하시면 됩니닷
우리 프로젝트에서는 DB 쿼리 모아놓은 곳이지 Club가져오는 곳은 아니예요.

다른 프로젝트에서는 club은 clubRepsitory에서 가져오는 방식으로 많이들 합니다.

2024-11-14 19:00 UTC, worjs commented on src/event/event.service.ts
> +  ) {}
Event 모듈에 훨씬 변경해야 할 사항들이 많을 것 같아요
클럽 모임 참가, 조회 등등 조건에서 고려해야 할 부분이 많습니다

2024-11-15 03:15 UTC, ggred0123 commented
아고.. 뭔가 빨리 끝내야겠다는 생각에 제가 좀 급했었던 것 같습니다 ㅜㅜ

2024-11-15 03:23 UTC, ggred0123 commented
뭔가 그리고 하다보니 몰입해서 생각없이 막~ 써버렸네요 ㅜㅜ

2024-11-15 05:56 UTC, ggred0123 commented on src/club/club.repository.ts
> +        status: 'PENDING',
넵 확인했습니다!

2024-11-15 05:57 UTC, ggred0123 commented on src/club/club.repository.ts
> +  }
넵 확인했습니다!

2024-11-15 05:58 UTC, ggred0123 commented on src/club/club.service.ts
> +    }
이벤트가 아니고 클럽이네용

2024-11-15 05:59 UTC, ggred0123 commented on src/club/club.service.ts
> +    }
하긴 웨이팅은 상관이 없을 수 있겠군요

2024-11-15 07:28 UTC, ggred0123 commented on src/club/club.service.ts
> +  }
boolean 으로 수정했습니다!

2024-11-15 07:41 UTC, ggred0123 commented on src/club/club.repository.ts
> +  }
음.. 일단 해보긴 했는데 eventrepository 를 끌어오는건 허용되지 않는다고 해서 그냥 event repository에 있는 메서드 몇개 가져와서 구성해보았습니다

2024-11-15 07:48 UTC, ggred0123 commented on src/club/club.service.ts
> +    await this.checkLeadPermissionOfClub(clubId, user.id);
확인했습니다!

2024-11-15 07:48 UTC, ggred0123 commented on src/club/club.service.ts
> +  ): Promise<ClubDto> {
확인했습니다!

2024-11-15 07:49 UTC, ggred0123 commented on src/club/club.controller.ts
> +  @Get(':ClubId')
넵!

2024-11-15 07:50 UTC, ggred0123 commented on src/club/club.service.ts
> +  }
어떤 검증이 필요한거...죠..?

2024-11-15 07:50 UTC, ggred0123 commented on src/club/club.service.ts
> +  }
제가 생각한 부분들 추가해보겠습니다!

2024-11-17 10:54 UTC, worjs commented
> 귀찮더라도 가능하면 기능별로 여러개의 PR로 나누어서 올려주시거나, 제가 이해할 수 있게 작업내용과 고려사항들을 별도로 문서화해서 넘겨주시는게 좋을 것 같습니다ㅎㅎ,,


부탁좀 드리겠습니다ㅠㅠ
기능별로, 변경별로 PR 나눠서 올려주세요,,,,
이대로는 저도 채점해드리기가 어려울 것 같고 리뷰 하는데도 한시간씩 걸려요ㅜㅜ

2024-11-17 10:55 UTC, worjs commented
팁 드리면 새로 만드는 API는 API별로 하나씩 만들어서 올려주시고, 각 api의 목적과 동작에 대해서 PR에 서술해주세요.
기존 API 수정의 경우에는 같은 컨셉의 변경을 묶어서 하나의 PR로 부탁드립니다.(soft delete 추가에 따른 기존 api 변경 이런식으로요!)

2024-11-17 11:13 UTC, worjs commented
https://quiet-airplane-930.notion.site/PR-141bbfebc135801f9d39e7c097119647?pvs=4

요기 브랜치 관리하는 방법도 준비해드렸으니 부탁드리겠습니다!!

2024-11-17 14:25 UTC, ggred0123 commented
아아 이제 정확히 이해했습니다. 제가 깃을 처음 써봐서 이런식으로 나눠주는 거라는걸 처음 알았습니다! 앞으로 이렇게 해보겠습니다! 내일 나누어놓겠습니다!

2024-11-18 13:12 UTC, closed without merging