첫번째 pr
ggred0123/nest-study-eventory-ymkim pull request #2
Opened 2024-10-28 06:56 UTC by ggred0123

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

작업을 하면서 조금의 궁금증이 있습니다. 
정확히 event를 만드는데에 있어 primarykey 가 되는 것이 무엇인지 모르겠습니다.
review에서는 userid와 eventid 가 합쳐진 eventId_userId 가 isReviewExist api 에서 쓰이고 있는데 
이와 관련하여 event는 그냥 hostid 하나가 primarykey의 역할을 하는지 아니면 따로 index.d.ts파일을 수정해야하는지 알고 싶습니다.

2024-10-28 08:15 UTC, worjs requested changes
고생하셨습니다!
수정할만한 부분은 코멘트로 작성해두었으니 참고하시면 되겠습니다~

혹시 코멘트를 읽어도 어려운 부분이 있다면 언제든지 직접 물어보세요!!

2024-10-28 08:15 UTC, worjs commented on src/event/dto/event.dto.ts
> +  title!: string;
요 이벤트의 ID가 보이지 않네요!

2024-10-28 08:15 UTC, worjs commented on src/event/event.service.ts
> +    }
한 호스트가 여러 날짜에 걸쳐 여러 모임을 만들 수도 있지 않을까요?

2024-10-28 08:15 UTC, worjs commented on src/event/event.service.ts
> +    }
마찬가지로, 새로운 모임을 생성하는 상황인데, 기존에 있는 모임을 가져와서 무언가 확인(검증)할 필요가 있을까요?

2024-10-28 08:15 UTC, worjs commented on src/event/event.service.ts
> +    }
hostId에 대한 예외처리 좋습니다. 그렇다면 만약에, categoryId나 cityId로 클라이언트에서 1000같은 값을 보내면 어떻게 될까요!

2024-10-28 08:15 UTC, worjs commented on src/event/event.service.ts
> +
함수의 이름이 적절하지 않은 것 같네요!

2024-10-28 08:15 UTC, worjs commented on src/event/query/event.query.ts
> +}
Issue를 한번 더 확인해주세요!
CategoryID나 CityID도 쿼리 조건이 있었습니다~

2024-10-28 08:15 UTC, worjs commented on src/event/payload/create-event.payload.ts
> +  maxPeople!: number;
사소하긴 한데 최대 인원 값을 1 이상으로 지정할 수 있으면 좋을 것 같은데 어떻게 생각하세요??

https://github.com/typestack/class-validator
요기서 적절한거 하나 찾아서 달아보세요ㅎㅎㅎ

2024-10-28 08:15 UTC, worjs commented on src/event/payload/create-event.payload.ts
> +  endTime!: Date;
Client에서는 '2022-02-01'과 같은 string을 Date 값으로 넘겨줄 수도 있습니다.
아마 Int로 Validation 해버리면 통과를 못할거예요!

https://github.com/typestack/class-validator
마찬가지로 적절한 데코레이터 한번 찾아보시면 되겠습니다~

2024-10-28 08:15 UTC, worjs commented on src/event/payload/create-event.payload.ts
> +  title!: string;
title은 String인데 Docs에는 Number로 되어있네용

2024-10-28 08:15 UTC, worjs commented on src/event/event.repository.ts
> +    });
event의 ID가 HostId일때의 Event를 반환하는 함수인가요??
무언가(?) 잘못된 것 같네요

2024-10-28 08:15 UTC, worjs commented on src/event/event.repository.ts
> +  }
이 두 함수는 같은 함수로 보이네요

2024-10-28 08:15 UTC, worjs commented on src/event/event.repository.ts
> +  }
마찬가지로, event의 Id에 hostID를 넘기면 잘못된 데이터가 딸려올 것 같아요!

2024-10-28 08:15 UTC, worjs commented on src/event/event.repository.ts
> +  }
eventJoin 테이블은 eventId와 userId를 하나씩 받아서 특정 유저가 특정 이벤트에 Join했는지에 대한 정보를 기록하는 ManyToMany 테이블입니다.

[이슈](https://github.com/worjs/nest-study-eventory/issues/14) 하단부에서도 언급한 것 처럼, 어떤 유저가 모임을 생성했다면, 해당 유저는 자연스레 참가한 것이 되겠죠? 즉, eventJoin에도 데이터를 추가해 주어야 합니다. 원래는 event를 생성하고 evendId를 받아와서 userId와 eventId를 가지고 다시 create문을 실행해야 하지만, prisma에서는 이렇게 연관테이블인 경우 연관해서 생성하는 기능을 갖고 있습니다.
https://www.prisma.io/docs/orm/prisma-client/queries/relation-queries#nested-writes
아래 링크를 참조하시면 도움을 얻을 수 있습니다!

2024-10-28 08:15 UTC, worjs commented
아 그리고, 이거 실행하면 아마 에러가 발생하는 것 같습니다. 한번 확인해보시면 좋을 것 같네용

2024-10-28 11:36 UTC, ggred0123 commented on src/event/dto/event.dto.ts
> +  title!: string;
요 이벤트의 id가 어떤걸 말하는 건가여?
{
  hostId: number,
  title: string,
  description: string,
  categoryId: number,
  cityId: number,
  startTime: Date,
  endTime: Date,
  maxPeople: number,
}
여기에 있는 것들만 적는거 아니었나요..?

2024-10-28 11:55 UTC, ggred0123 commented on src/event/event.repository.ts
> +  }
일단 했는데 제가 맞게 했는지 모르겠네요.. 저는 일단 저 문서를 보고 repository쪽만 수정했는데 정확히 어떻게 해야할지 모르겠네요..ㅜ
nested create 를 하기 위해 data 안에다가 eventJoin을 넣은 다음에 eventid와 userid를 넣고 싶은데 
eventid가 EventJoinCreateWithoutEventInput 타입을 정의할 때 쓰여있지 않아 쓸 수 없는 문제가 있고 
지금 코드에는 userId만 쓰여있는데 여기다가 어떤 값을 할당해야할지 몰라 일단 data.hostId로 적어 놨습니다.. 
이번 과제... 꽤나 흥미롭게 어렵네요..ㅜㅠ

2024-10-28 12:02 UTC, ggred0123 commented on src/event/dto/event.dto.ts
> +  title!: string;
아직 과제 안의 데이터들에 대한 명확한 이해가 되지 않은 것 같습니다..ㅜ

2024-10-28 12:02 UTC, ggred0123 commented on src/event/event.service.ts
> +    }
확인했습니다!

2024-10-28 12:02 UTC, ggred0123 commented on src/event/event.service.ts
> +    }
따로 예외처리 해보겠습니다!

2024-10-28 12:03 UTC, ggred0123 commented on src/event/event.service.ts
> +
확인했습니다

2024-10-28 12:03 UTC, ggred0123 commented on src/event/payload/create-event.payload.ts
> +  title!: string;
확인했습니다!

2024-10-28 12:03 UTC, ggred0123 commented on src/event/event.repository.ts
> +    });
넵 확인했습니다!

2024-10-28 12:03 UTC, ggred0123 commented on src/event/event.repository.ts
> +  }
아 확인했습니다!

2024-10-28 12:05 UTC, ggred0123 commented on src/event/event.repository.ts
> +  }
여기도 정확히 어떤걸 집어넣어야할지 잘 모르겠어서 일단 id:id로 넣었습니다! event type안에 정의되어 있는게 들어가야하는거 아닌가요..?

2024-10-28 12:25 UTC, worjs commented on src/event/dto/event.dto.ts
> +  title!: string;
모임을 생성하기 전 Response Body에는 event라는 데이터의 id가 없지만, 생성 후 response로 반환하는 데이터는 모임을 생성한 이후니까 모임 id가 생겼을거예요! 과제 페이지에서도 response body에 포함되어 있습니다!

2024-10-28 13:43 UTC, worjs requested changes

2024-10-28 13:43 UTC, worjs commented on src/event/event.repository.ts
> +      },
오 요거 맞아요
event 생성하면서 생성된 event와 연관된 eventjoin도 같이 만들어준다는 컨셉이라서, 자동으로 eventId는 새로 생성된 값이 들어갑니다. 그러고 userId는 host의 Id가 들어가는게 맞구요.

2024-10-28 13:43 UTC, worjs commented on src/event/event.repository.ts
> +  }
요 두 코드도 마찬가지로 userId로 조회해야하는데 카테고리나 도시 ID를 넣으면 원하는 결과가 안나오지 않을까요?

2024-10-28 13:43 UTC, worjs commented on src/event/event.repository.ts
> +  }
엄청 사소한 부분이긴 한데, 엄밀히 말하면 Id가 hostId인 User을 가져오는거라 함수 이름이 getUserById(userId)가 좋지 않을까 하는 생각이 드네요!

2024-10-28 13:43 UTC, worjs commented on src/event/event.service.ts
> +    if (!event) {
정원을 확인해야한다는 부분을 찾으셨네요!
위 코드는 몇 가지 문제점이 있습니다.
1. maxPeople 값은 고정입니다. 다른 코드에서 event를 조회할때, maxPeople값도 내려주고 있습니다. maxPeople이라는건 최대 정원이라는 의미인데, 사람이 join할때마다 정원이 줄어드는건 직관적이지는 않은 것 같습니다.
2. DB에서 가져온 값을 변형했다면 다시 update하는 요청을 보내야 반영이 됩니다ㅎㅎ 위에 작성된 코드는 아마 효과가 없을겁니다.

그러면 대신 정원을 파악하기 위해서는eventJoin 테이블에서, 우리가 원하는 event의 Id을 eventId로 가지고 있는 데이터의 개수를 가져와서 세보면 되겠죠?

2024-10-28 13:43 UTC, worjs commented on src/event/payload/create-event.payload.ts
> +  endTime!: Date;
혹시 직접 값을 넣고 테스트 해보셨나요?
아마 통과가 안될건데, 내부적으로 값이 들어올때 number 또는 string으로 들어오기 때문에 명시적으로 type이 변환해주어야 Isdate를 통과할 수 있습니다.

위 내용은 좀 어려운 내용이어서...
@Type(()=> Date) 였나... 이걸 하나씩 달아주면 잘 작동할거예요!

2024-10-28 13:44 UTC, worjs commented
고생하셨습니다-! 코멘트 몇개 드렸으니 확인해보세요 !

2024-10-29 01:57 UTC, ggred0123 commented on src/event/event.repository.ts
> +      },
오 다행히 맞았군요!

2024-10-29 03:47 UTC, ggred0123 commented on src/event/payload/create-event.payload.ts
> +  endTime!: Date;
import { Type } from 'class-transformer';
쿼리에서 쓰인 이거 가져온 다음에 
 @IsDate()
  @Type(() => Date)
이렇게 사용하는 것으로 수정했습니다.

2024-10-29 06:07 UTC, ggred0123 commented on src/event/event.repository.ts
> +  }
이게 where 부분이 filter 역할을 해줘서 category id나 도시 id 만 들어왔을때 그부분에 대해서 find를 해주는 방식으로 작동하는게 아닌가요..? 어떤 방향으로 수정이 이루어져야하나요?

2024-10-29 06:11 UTC, ggred0123 commented on src/event/event.repository.ts
> +  }
async getUserById(userId: number): Promise<User | null> {
    return this.prisma.user.findUnique({
      where: {
        id: userId,
      },
    });
  }
  이런 느낌으로 이루어지는건가요?

2024-10-29 06:11 UTC, worjs commented on src/event/event.repository.ts
> +  }
맞습니다

다만 조회하고 있는 테이블(도메인)이 user인게 문제가 됩니다.

> 저 코드는 유저의 ID가 카테고리 ID인 유저를 주세요
라는 의미가 되는데, 이상하죠.. 

만약에 목적이 특정 도시에 사는 유저를 모두 조회해주세요 라면, cityId: cityId라고 할 수는 있겠지만 그 목적이 아니기도 하고요.

위에 작성한 코드로 어떤 것을 하고 싶으신가요?

2024-10-29 06:13 UTC, ggred0123 commented on src/event/event.service.ts
> +    if (!event) {
아 그렇군요! 새로운 변수를 지정하기가 너무 복잡할 것 같아서 maxPeople을 줄이는 방식을 써보려고 했는데 
eventJoin 테이블에서 eventid 카운트 하는 방식으로 한번 접근해보겠습니다!

2024-10-29 06:22 UTC, worjs commented on src/event/event.repository.ts
> +  }
네네 그쵸 사실 user를 가져오는거니까요
마침 들고있는 userId가 hostId라는 값인 거구요!

2024-10-29 06:23 UTC, ggred0123 commented on src/event/event.service.ts
> +    if (!event) {
<img width="486" alt="스크린샷 2024-10-29 오후 3 23 04" src="http
<img width="491" alt="스크린샷 2024-10-29 오후 3 23 46" src="https://github.com/user-attachments/assets/3bf35e85-3c7b-442d-8bad-deed7b8aa280">
s://github.com/user-attachments/assets/ee77cf79-0455-4d77-b413-03d7cf0dd15a">

정확히 eventJoin 테이블의 데이터에 접근하는 방식이 이해가 가지 않습니다. event에서 했던 것처럼 datatype 을 만들어서 해야하는 건가요?

2024-10-29 06:27 UTC, worjs commented on src/event/event.service.ts
> +    if (!event) {
그쵸그쵸 eventJoin이라는 테이블은 event랑은 다른 테이블이니까요

근데 저는 굳이 Response에 들어가야하는 경우가 아니라면 굳이 타입을 새로 만들 필요까진 없다고 생각해요.
아마 EventJoin이라는 @prisma/client가 만들어준 타입이 있을겁니다.

2024-10-29 06:42 UTC, ggred0123 commented on src/event/event.repository.ts
> +  }
아아 카테고리와 도시 당연히 모두 각자의 도메인에서 가져와야하군요.. 감사합니다!

2024-10-29 06:42 UTC, ggred0123 commented on src/event/event.repository.ts
> +  }
넵 확인했습니다!

2024-10-29 07:24 UTC, ggred0123 commented on src/event/event.service.ts
> +    if (!event) {
넵 event join 찾아서 새로운 count 하는 api 만들어서 적용시켰습니다(index.d.ts eventjoin 부분의 count aggregate 사용)! 감사합니다!

2024-10-29 07:38 UTC, ggred0123 commented on src/event/payload/create-event.payload.ts
> +  endTime!: Date;
제가 지금 집이 아니라서 집에서 실행해보고 다시 커밋해서 올려보겠습니다!

2024-10-29 15:02 UTC, ggred0123 commented
1. 모임을 만드는 api에서
![image](https://github.com/user-attachments/assets/193273ee-93a6-4490-a638-2c81c26e0832)
이런 에러가 뜹니다..
2. 모임에 join 하는 api는 처음에 리턴타입에 eventdto가 아닌 것을 깨 닫고 apiokresponse 부분을 없앴고, userId 부분에 parseintpipe를 했더니 validation error가 떠서
![image](https://github.com/user-attachments/assets/6cd7c5fe-dc9c-43bc-89dc-ee1ab609ce1a)
이와 같이 작업 후 돌려보니
![image](https://github.com/user-attachments/assets/329ae35d-3f9d-4a15-9c8e-bca0b7add711)
이렇게 뜹니다. 이 문제는 docs에서 시험할 때 userId를 삽입하는 부분이 나오지 않아 넣을 수가 없는게 문제 같습니다.

2024-10-29 15:13 UTC, worjs commented
흠 1번문제는 아마도? 제 예상에는 hostId로 어떤 userId를 넘겨주셨을텐데, user 테이블에 데이터가 없어서 그런 것 같습니다.
supabase에 가셔서 직접 user 테이블에 데이터 하나 넣어주면 해결될 것 같아요

2번문제는 음... 그냥 전반적으로 잘못된 것 같은데, userId를 모임 생성때처럼 payload 만들어서 넘겨주는건 어떠신가요?
아님 `@Body('userId', ParseIntPipe) userId: number` 이렇게 해주면 될거같기도 하고...

2024-10-29 15:25 UTC, ggred0123 commented
이게 1번에서 user table에 2개의 데이터를 1,2로 넣었는데 
![image](https://github.com/user-attachments/assets/a25c3c6e-c97b-4f2a-af68-8cae9f53db99)
![image](https://github.com/user-attachments/assets/e5991b57-3374-4915-88f0-9e9e5bba228f)
![image](https://github.com/user-attachments/assets/81715879-fce9-4e20-977a-f9e9c0752e3e)
이렇게 나옵니다..



그리고 2번 같은 경우에 맨 처음에 코드를 저렇게 했었다가 
![image](https://github.com/user-attachments/assets/8af5caf7-1faa-4b51-ab55-f44074749db2)
이 에러를 마주하고 string 으로 고치니까 userid를 입력하지 않았다는 메세지로 바뀌었습니다(입력하는 부분 자체가 없음)

2024-10-29 15:32 UTC, worjs commented
어라라 뭐지... 혹시 yarn db:save:db 한번 돌려보실래요

2번은 새로 payload만드시면 해결될듯

2024-10-29 15:42 UTC, ggred0123 commented
으음..
yarn run v1.22.22
warning ..\..\package.json: No license field
error Command "db:save:db" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
이렇게 뜨네요...

2024-10-29 15:45 UTC, ggred0123 commented
payload는 createEventJoinPayload 로 새로 만드는거 맞나요..?

2024-10-30 07:03 UTC, worjs requested changes
진짜진짜 거의 다 왔습니다~~ 이제 빠진 요구사항들만 조금 추가하면 될 것 같아요!!
조금만 더 화이팅!!!

2024-10-30 07:03 UTC, worjs commented on src/event/dto/event.dto.ts
> +  description!: string;
swagger type nullable <- 요거 바꿔야 할듯!

2024-10-30 07:03 UTC, worjs commented on src/event/event.controller.ts
> +}
아무것도 return하지 않고 있어서, swagger 데코레이터를 ApiNoContent로 하는게 좋아보이네요!

2024-10-30 07:03 UTC, worjs commented on src/event/event.repository.ts
> +
이거 이렇게 넣으면 eventJoin의 Id가 eventId인게 EventJoin이 나올것 같은데요??

2024-10-30 07:03 UTC, worjs commented on src/event/event.repository.ts
> +  }
함수 이름이 여전히 틀린 것 같습니다~~

2024-10-30 07:03 UTC, worjs commented on src/event/event.service.ts
> +    }
요기도 마찬가지로 변수 이름이 바뀌면 좋겠네요!

2024-10-30 07:03 UTC, worjs commented on src/event/event.service.ts
> +    }
eventCount라는 이름을 모르는 사람이 봐도 현재 이벤트에 참가한 사람 수라는 것을 알 수 있을까요?

2024-10-30 07:03 UTC, worjs commented on src/event/event.service.ts
> +    }
호스트가 자기가 만든 모임에서 나가는 경우도 고려하면 좋겠네요! 그러면 안될 것 같거든요

2024-10-30 07:03 UTC, worjs commented on src/event/payload/create-eventJoin.payload.ts
> +}
모임에서 들어갈때도, 나갈때도 이 payload를 받는건데, 조금 더 좋은 이름이 있을 것 같군요.

2024-10-30 07:03 UTC, worjs commented on src/event/event.service.ts
> +  async joinEvent(eventId: number, userId: number): Promise<void> {
요구사항을 보면, 이벤트의 참가/탈퇴는 이벤트 시작 전이라는 요구사항이 있습니다!
그 부분도 고려해야 할 것 같아요

2024-10-30 07:03 UTC, worjs commented on src/event/event.service.ts
> +
아직 숨겨져있는(?) 예외사항들이 좀 더 있습니다.
주로 모임 시간에 관련된 부분이예요.

2024-10-30 07:51 UTC, ggred0123 commented on src/event/event.service.ts
> +
두개 정도 예외사항 추가했습니다!

2024-10-30 07:51 UTC, ggred0123 commented on src/event/event.service.ts
> +  async joinEvent(eventId: number, userId: number): Promise<void> {
확인했습니다!

2024-10-30 07:51 UTC, ggred0123 commented on src/event/payload/create-eventJoin.payload.ts
> +}
확인했습니다!

2024-10-30 07:51 UTC, ggred0123 commented on src/event/event.service.ts
> +    }
확인했습니다!

2024-10-30 07:51 UTC, ggred0123 commented on src/event/event.service.ts
> +    }
currentPeople 로 바꿔보겠습니다

2024-10-30 07:51 UTC, ggred0123 commented on src/event/event.service.ts
> +    }
확인했습니다!

2024-10-30 08:02 UTC, ggred0123 commented on src/event/event.repository.ts
> +
그냥 id 로 수정했습니다!

2024-10-30 08:05 UTC, ggred0123 commented on src/event/event.repository.ts
> +  }
확인했습니다!

2024-10-30 08:05 UTC, ggred0123 commented on src/event/event.repository.ts
> +
확인했습니다!

2024-10-30 08:06 UTC, ggred0123 commented on src/event/event.repository.ts
> +
아 근데 또 제 service에 이게 아에 안쓰여서 애매하네요..

2024-10-30 08:29 UTC, worjs commented on src/event/event.repository.ts
> +
안쓰면 지우면 되죠(?)

2024-10-30 08:36 UTC, worjs approved these changes
LGTM! 수고하셨습니다~~

코멘트 2개가 더 있는데 요거는 저한테 다시 리뷰 받으실 필요는 없고, 고친 다음에 바로 머지하시면 되겠습니다!!

고생하셨어요~~~~~~🎉🎉🎉🎉🎉🎉

2024-10-30 08:36 UTC, worjs commented on src/event/event.service.ts
> +    }
요거는 그냥 바로 밑에서 가져온 event 객체 가지고 확인해도 될 것 같은데요?

2024-10-30 08:36 UTC, worjs commented on src/event/event.service.ts
> +    }
endTime 이후를 막은건데 에러 메세지는 이미 시작된 이벤트라고 나와있어요.
내부에서 어떻게 구현했는지 모르는 클라이언트 개발자 입장에서는 이상하게 생각할 수도 있을 것 같네요.

에러 메세지를 바꾸던가, startTime을 기준으로 바꾸던가 둘 중에 하나를 하면 되겠습니다!
위에서도 비슷한 에러메세지가 있었어요.

2024-10-30 08:51 UTC, ggred0123 commented on src/event/event.service.ts
> +    }
수정했습니다!

2024-10-30 08:53 UTC, merged

2024-10-30 09:01 UTC, ggred0123 commented
감사합니다!

2024-10-30 09:01 UTC, ggred0123 commented on src/event/event.service.ts
> +    }
확인했습니다!