클럽 참가 api 구현
ggred0123/nest-study-eventory-ymkim pull request #21
Opened 2024-11-18 15:00 UTC by ggred0123

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [ v] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
클럽 참가 api 구현해보았습니다.

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-20 08:52 UTC, worjs requested changes
만약에 유저가 이미 waiting을 걸어둔 상태에서 이 api를 요청한다면 어떻게 되나요?

2024-11-20 08:52 UTC, worjs commented on src/club/club.repository.ts
> +        status: 'PENDING',
Enum을 정의하고 이렇게 문자열을 그대로 가져다 쓰게 되면 enum을 사용하는 의미가 없다.. 까진 아니지만 약간 아쉬워지게 됩니다.

WaitingStatus.PENDING
이런 형태로 쓸 수 있을거예요

2024-11-20 08:52 UTC, worjs commented on src/club/club.repository.ts
> +    const Club = await this.prisma.clubJoin.findUnique({
사실 바로 !!붙여버리고 리턴할건데 이름이 뭐 대수야? 싶겠지만, 만약에 prisma에 익숙하지 않은 다른 개발자가 이 코드를 보고 엥 club을 리턴하는거야? 라고 헷갈려할수도 있거든요.

변수 이름은 언제나 너무 잘 지을필요까진 없어도 적절한 수준까진 만들어줘야 합니다ㅎㅎ

2024-11-20 09:22 UTC, ggred0123 commented on src/club/club.repository.ts
> +        status: 'PENDING',
넵 확인했습니다!

2024-11-20 09:23 UTC, ggred0123 commented on src/club/club.repository.ts
> +    const Club = await this.prisma.clubJoin.findUnique({
넵 알겠습니다!

2024-11-20 10:26 UTC, worjs commented
혹시 완성하시면 re-request 부탁드려용
그리고 이대로 머지하면 아마 힘들어질거고 
꼭 업데이트된 dev를 로컬에서 rebase하고 푸시하셔야 할겁니다~~

++ PR 베이스도 dev로 변경

2024-11-20 11:02 UTC, ggred0123 commented
음.. feat_1 을 머지한 상태여서
<img width="417" alt="스크린샷 2024-11-20 오후 8 01 27" src="https://github.com/user-attachments/assets/32d5403f-7f58-4529-93c9-d3c11b23b4e5">
feat_2에서 rebase 했더니 위와 같이 됐는데 이 상태에서 머지할까요..?

2024-11-20 14:10 UTC, worjs commented
force 푸시하고 PR베이스 변경해주세요!
드린 문서에 다 나와있긴 한데 그대로 하시면 됩니당
왜 이렇게 해야하는지 이해해보는 것도 좋은 공부가 될듯 하네요!

2024-11-20 14:15 UTC, worjs approved these changes
굳! 혹시 이런 케이스는 생각해보셨나요?

만약에 어떤 유저가 신청했는데 거절당했습니다. 그런데 또 신청하면 어떻게 될까요?

2024-11-21 09:24 UTC, merged

2024-11-21 09:39 UTC, worjs commented
ㅠㅠㅠ

```
force 푸시하고 PR베이스 변경해주세요!
드린 문서에 다 나와있긴 한데 그대로 하시면 됩니당
왜 이렇게 해야하는지 이해해보는 것도 좋은 공부가 될듯 하네요!
```

2024-11-21 09:44 UTC, worjs commented on src/club/club.service.ts
> +    }
제가 말씀드린 목적은, 이런 부분이야말로 명확하지 않으니 직접 개발하시면서 이런저런 상황들을 고민하다가 저한테 질문을 해달라는 것이었습니다ㅎㅎ

결국 기획이 챙기지 못한건 개발하는 사람이 책임지고 챙겨야 하니까요.

개발할때 아래와 같은 흐름이 나와야 좋습니다.

```
처음에는 몰랐는데 개발을 해놓고 보니, 현재 구조에서는 한번 거절당한 사람들은 재 신청을 하면 로직에서 막히게 된다.

그럼 거절당한 사람들은 다시 참가하지 못하게 하는게 맞나? 아니면 다시 참가할 수 있지 않을까?
혹시 승인을 받았었는데 자진해서 클럽을 나간 사람들은 어떻게 되나?

기획이 애매하니 다시 물어봐야겠다
```

2024-11-21 09:53 UTC, ggred0123 commented
오.. 깃 뭔가 잘못된건가요..?

2024-11-21 09:54 UTC, ggred0123 commented on src/club/club.service.ts
> +    }
아 이런 부분을 질문드리라는 말씀이셨군요

2024-11-21 10:01 UTC, worjs commented
대형사고는 아니긴한데ㅋㅋㅋ feat_1에다 머지했으니까 main에 다시 머지해야하는... 거죠ㅋㅋㅋ

```
force 푸시하고 PR베이스 변경해주세요!
드린 문서에 다 나와있긴 한데 그대로 하시면 됩니당
왜 이렇게 해야하는지 이해해보는 것도 좋은 공부가 될듯 하네요!
```

요거 혹시 이해가 안되셨나요

2024-11-21 10:07 UTC, ggred0123 commented
아 pr 베이스라는게 합쳐지는 브랜치를 의미하는거였군요.. 전 그냥 처음에 뜨는 default 브랜치를 말한 건 줄 알았네요..ㅜ