클럽 내 모임 생성에 따른 create event 수정
ggred0123/nest-study-eventory-ymkim pull request #22
Opened 2024-11-18 15:09 UTC by ggred0123

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- v[ ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?

클럽 내 모임 생성에 따른 create event 수정하였고 join event나 이런 것들은 아직 건드리지 않았습니다.

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-20 08:55 UTC, worjs requested changes
클럽원이 아닌 사람도 club id만 알면 모임을 생성할 수 있는 상황이 되네요!

2024-11-20 08:55 UTC, worjs commented on src/event/dto/event.dto.ts
> +      clubId: event.club ? event.club.id : null,
JS문법에는 `event.club ?? null` 이 같은 효과를 낼 것 같네용

2024-11-20 08:55 UTC, worjs commented on src/event/payload/create-event.payload.ts
> +
null을 넣고 테스트를 한번 해보셔야 할듯!

2024-11-20 08:55 UTC, worjs commented on src/event/type/create-event-data.type.ts
> +  clubId?: number | null;
현재 작성하신 코드를 보면 clubId가 undefined일 가능성은 없어보입니다!

2024-11-20 09:27 UTC, ggred0123 commented on src/event/dto/event.dto.ts
> +      clubId: event.club ? event.club.id : null,
오옹 일단 수정해보았습니다

2024-11-20 09:31 UTC, ggred0123 commented on src/event/payload/create-event.payload.ts
> +
아 isnullable 데코레이터와 apipropertyoptional을 넣겠습니다!

2024-11-20 09:32 UTC, ggred0123 commented on src/event/type/create-event-data.type.ts
> +  clubId?: number | null;
오.. 그런가요?

2024-11-20 09:33 UTC, ggred0123 commented on src/event/type/create-event-data.type.ts
> +  clubId?: number | null;
조금 더 고민해보겠습니다!

2024-11-20 14:18 UTC, worjs requested changes

2024-11-20 14:18 UTC, worjs commented on src/event/payload/create-event.payload.ts
> +  clubId!: number | null;
clubId를 undefined로 해서 필드 없이 요청해보시겠어요?

2024-11-21 09:33 UTC, ggred0123 commented on src/event/payload/create-event.payload.ts
> +  clubId!: number | null;
수정하겠습니다!

2024-11-24 08:38 UTC, worjs requested changes
실제로 테스트 해보셨나요?

repository 코드에서 clubId 추가해서 쿼리 날려야하는데 그거 빠져있네요ㅎㅎ

2024-11-24 08:38 UTC, worjs commented on src/event/event.service.ts
> +        throw new ForbiddenException('이 클럽에 속해있지 않습니다.');
"클럽 모임은 클럽원만 개설할 수 있습니다" 가 더 좋을 것 같습니다!

2024-11-24 09:01 UTC, ggred0123 commented on src/event/event.service.ts
> +        throw new ForbiddenException('이 클럽에 속해있지 않습니다.');
확인했습니다!

2024-11-24 09:01 UTC, ggred0123 commented
수정해보겠습니다!

2024-11-25 04:12 UTC, worjs approved these changes
LGTM!

2024-11-25 04:25 UTC, merged