클럽 조인 승인 api 구현
ggred0123/nest-study-eventory-ymkim pull request #23
Opened 2024-11-18 15:28 UTC by ggred0123

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [v ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?

클럽 조인 승인 api 구현해보았습니다.

2024-11-20 09:07 UTC, worjs requested changes
좋아요좋아요

2024-11-20 09:07 UTC, worjs commented on src/club/club.repository.ts
> +        status: 'PENDING',
enum 관련 이전PR에서 드린 코멘트 참고!

2024-11-20 09:07 UTC, worjs commented on src/club/club.service.ts
> +  }
흠 그럼 지금 approveClubJoin이라는 이 서비스 함수는 
`const club = await this.clubRepository.getClubById(clubId);`
얘를 두번 호출하는 셈이 되는군요

2024-11-20 09:07 UTC, worjs commented on src/club/club.service.ts
> +    }
else문은 많은 상황에서 코드 흐름을 꽤 복잡하게 만든다는 생각을 갖고 있습니다.

지금이야 단순하게 마지막에 간단한 분기를 하고 있는데, 만약에 if문이 중첩되거나, else if문이 끼거나, 아래쪽에서 또 if문이 나오게 되면... 경우의 수룰 파악하다가 머리가 아파집니다.

if문을 활용하는 좋은 방법은, if문을 열었을 때 바로 함수를 탈출할 수 있는 상황이라면 탈출하라는 것입니다.
if문을 사용하면 조건이 분기되기 때문에 경우의 수가 생기는데요, return이나 throw를 통해 바로 탈출해버리면 그 아래 코드 흐름에서 해당 분기를 고려할 필요가 없어지기 때문에 파악이 쉬워지는것이죠.

위 코드도, 

```
if (!approve) {
      await this.clubRepository.rejectClubJoin(clubId, userId);
      return;
    } 

    await this.clubRepository.approveClubJoin(clubId, userId);
    
```

위와 같이 해버리면 if문 하나로 충분해지게 되겠죠!

물론 항상 가능한건 아니고, 가능하면 if문 열고 탈출을 통해 분기들을 잘 쳐주면 좋다~ 그런 의미입니다.

2024-11-20 09:07 UTC, worjs commented on src/club/club.service.ts
> +    }
그리고 이건 진짜 그냥 취향인데
저는 위와 같은 상황에서 if(approve)를 쓰고 나머지를 else로 둘 것 같아요.
그냥 부정보다 긍정이 생각하기 쉬워서(?)

2024-11-20 09:07 UTC, worjs commented on src/club/payload/approve-club-join.payload.ts
> +import { Type } from 'class-transformer';
안쓰는 import는 삭제!

2024-11-20 09:36 UTC, ggred0123 commented on src/club/club.repository.ts
> +        status: 'PENDING',
넵!

2024-11-20 09:38 UTC, ggred0123 commented on src/club/club.service.ts
> +  }
확인했습니다!

2024-11-20 09:40 UTC, ggred0123 commented on src/club/club.service.ts
> +    }
확인했습니다!

2024-11-20 14:21 UTC, worjs requested changes

2024-11-20 14:21 UTC, worjs commented on src/club/club.controller.ts
> +  }
엌 깜짝아
제가 리뷰를 제대로 안했었군요
이게 제대로 된 api가 맞나요?

테스트를 한번 해보셔야 할듯!

2024-11-20 14:43 UTC, ggred0123 commented on src/club/club.controller.ts
> +  }
넵 수정했습니다!

2024-11-21 06:03 UTC, worjs approved these changes
그 외에는 ok!

2024-11-21 06:03 UTC, worjs commented on src/club/club.controller.ts
>  }
이 경우에는 :/clubId/users/:userId/approve로 하시는게 좋습니다ㅎㅎ
하지만 저는 payload에 들어가도 좋지 않을까? 하는 생각이 드네요.

2024-11-21 06:03 UTC, worjs commented on src/club/club.controller.ts
>  }
204 NoContent를 하려면 `@HttpCode(204)`

2024-11-21 06:19 UTC, ggred0123 commented on src/club/club.controller.ts
>  }
넵 확인했습니다!

2024-11-21 06:28 UTC, ggred0123 commented on src/club/club.controller.ts
>  }
payload로 바꿔보았습니다!

2024-11-25 04:43 UTC, merged