update club api 구현
ggred0123/nest-study-eventory-ymkim pull request #24
Opened 2024-11-18 15:29 UTC by ggred0123

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?

update club api 구현해보았습니다.

2024-11-20 09:11 UTC, worjs requested changes
LeadId 관련해서 놓치신듯(?)

2024-11-20 09:11 UTC, worjs commented on src/club/club.service.ts
> +      leadId: user.id,
leadId 검증!

2024-11-20 09:11 UTC, worjs commented on src/club/club.repository.ts
> +  }
leadId?

2024-11-20 09:46 UTC, ggred0123 commented on src/club/club.service.ts
> +      leadId: user.id,
await this.checkLeadPermissionOfClub(clubId, user.id);

    const updateData: UpdateClubData = {
      name: payload.name,
      leadId: user.id,
      description: payload.description,
      maxPeople: payload.maxPeople,
    };
    이렇게 체크하는 것 만으로는 좀 부족한 건가요..?

2024-11-20 09:52 UTC, ggred0123 commented on src/club/club.repository.ts
> +  }
아 확인했습니다!

2024-11-20 09:53 UTC, ggred0123 commented on src/club/club.service.ts
> +      leadId: user.id,
일단 고쳐보았습니다!

2024-11-20 10:46 UTC, worjs commented on src/club/club.service.ts
> +      leadId: user.id,
근데 그건 현재 요청자가 리드인지 확인하는 함수니까요..?
updateClubData에 저 값이 들어가는게 맞나요 근데

2024-11-20 11:29 UTC, ggred0123 commented on src/club/club.service.ts
> +      leadId: user.id,
확인했습니다!

2024-11-20 14:28 UTC, worjs requested changes

2024-11-20 14:28 UTC, worjs commented on src/club/club.controller.ts
> +    return this.ClubService.patchUpdateClub(clubId, payload, user);
이제 봤는데 변수는 camelCase!

2024-11-20 14:28 UTC, worjs commented on src/club/club.repository.ts
> +          status: WaitingStatus.APPROVED,
굿

2024-11-20 14:28 UTC, worjs commented on src/club/club.repository.ts
> +        leadId: data.leadId ?? undefined,
음 여기서 이 코드 `?? undefined` 는 필요한 이유가 뭘까요?

2024-11-20 14:28 UTC, worjs commented on src/club/club.service.ts
> +    }
lead!

2024-11-20 14:28 UTC, worjs commented on src/club/club.service.ts
> +      leadId: payload.leadId ?? undefined,
여기도 ! 이 코드가 왜 필요할까요?

2024-11-20 14:28 UTC, worjs commented on src/club/club.service.ts
> +      const userInClub = await this.clubRepository.isUserJoinedClub(
이름만 보면 "club에 있는 user" 자체를 나타내는 것 처럼 보여요

2024-11-21 05:39 UTC, ggred0123 commented on src/club/club.service.ts
> +      leadId: payload.leadId ?? undefined,
아아 위에서 null 체크를 안해서 오류 났던거를 leadId 데이터 특성으로 착각했습니다!

2024-11-21 05:39 UTC, ggred0123 commented on src/club/club.service.ts
> +    }
넵!

2024-11-21 06:17 UTC, ggred0123 commented on src/club/club.service.ts
> +      const userInClub = await this.clubRepository.isUserJoinedClub(
수정하겠습니다!

2024-11-24 08:26 UTC, worjs approved these changes
LGTM!

코멘트 하나는 반영해주시고 머지하시면 될듯

2024-11-24 08:26 UTC, worjs commented on src/club/club.controller.ts
> +    return this.ClubService.patchUpdateClub(clubId, payload, user);
이거 여전히..!

2024-11-25 04:59 UTC, merged