이벤트 조인 약간 수정, 클럽 탈퇴 api 구현
ggred0123/nest-study-eventory-ymkim pull request #25
Opened 2024-11-22 06:48 UTC by ggred0123

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

클럽에 탈퇴하는 api를 구현할 때 그 유저가 만들어둔 event가 있을 때 그 이벤트가 모두 삭제되는 형식인지 아니면 다른 방법으로 처리되는지 여쭤보고 싶습니다!

2024-11-24 08:22 UTC, ggred0123 commented
검토 부탁드립니다! @worjs

2024-11-24 15:54 UTC, worjs commented
별도로 삭제되지 않는게 맞을 것 같네요!

2024-11-24 15:54 UTC, worjs commented
근데 이미 시작되지 않은 이벤트면 없어지는게 맞을지도?

2024-11-25 04:21 UTC, ggred0123 commented
그렇게 바꿔보았습니다!

2024-11-25 04:37 UTC, worjs requested changes

2024-11-25 04:37 UTC, worjs commented on src/club/club.service.ts
> +    await this.clubRepository.checkEventStartedAndDeleteOrOut(events, user.id);
오 이거 투머치인듯요ㅋㅋㅋ
서비스에서 처리해줘야 할 코드가 레포지토리로 넘어간 것 같습니다

myEvents를 가져왔으니까, 거기서 삭제 대상인 이벤트를 골라내는건 서비스에서 하는게 맞을 것 같아요.
레포한테는 그냥 이 이벤트들 지워! 하는게 맞구요.

2024-11-25 04:37 UTC, worjs commented on src/club/club.service.ts
> +    await this.clubRepository.checkEventStartedAndDeleteOrOut(events, user.id);
그리고 write 쿼리는 한 transaction 처리 해주셔야함 !

2024-11-25 04:37 UTC, worjs commented on src/club/club.repository.ts
> +  }
요거는 이제 안쓰는거죠
근데 그런 경우도 있겠네요
내가 클럽 모임에 들어갔는데 그게 시작되지는 않았는데 나가려는거죠
그 경우도 똑같이 처리하는게 맞겠는데요?
시작되지 않은 경우엔 이벤트 나가고, 시작된 경우에는 참여한 이벤트 기록으로 남는거고

2024-11-25 05:05 UTC, ggred0123 commented on src/club/club.service.ts
> +    await this.clubRepository.checkEventStartedAndDeleteOrOut(events, user.id);
> 그리고 write 쿼리는 한 transaction 처리 해주셔야함 !

요게 무슨말이죠..?

2024-11-25 05:07 UTC, ggred0123 commented on src/club/club.repository.ts
> +  }
async outOrDeleteEvent(event: EventData, userId: number): Promise<void> {
    if (event?.hostId === userId) {
      await this.deleteEvent(event.id);
    } else await this.outEvent(event.id, userId);
  }
요고 구현할 때 쓰이긴 하는데..
구현 방식을 바꾸는게 좋을까요?

2024-11-25 05:10 UTC, ggred0123 commented on src/club/club.repository.ts
> +  }
아니면 이 부분을 transaction으로 바꾸라는 말씀이신가요?

2024-11-25 05:58 UTC, worjs requested changes

2024-11-25 05:58 UTC, worjs commented on src/club/club.service.ts
> +    await this.clubRepository.outClub(clubId, user.id);
흐으음 한 트랜잭션으로 처리하려면 myevents 조회하는 코드부터 전부 clubRepository.outClub 함수 안으로 들어가는 수밖에 없겠네요.

2024-11-25 05:58 UTC, worjs commented on src/club/club.service.ts
> +    await this.clubRepository.outClub(clubId, user.id);
쟤네들 다 outClub 안으로 밀어넣고, 이벤트 나가기, 삭제, 클럽 나가기 이 모든게 전부성공/전부실패로 처리되도록 구현해주시면 되겠습니다

2024-11-25 06:32 UTC, ggred0123 commented on src/club/club.service.ts
> +    await this.clubRepository.outClub(clubId, user.id);
orm 보고 참고해서 구현해보았습니다!

2024-11-25 09:44 UTC, worjs requested changes

2024-11-25 09:44 UTC, worjs commented on src/club/club.repository.ts
> +      }
진짜 마지막!
요거를 쿼리 두방으로 처리할 수 있을까요?

이렇게 작성하면 event 개수에 따라 수십 수백방의 쿼리가 병렬도 아니고 직렬(?)로 날아가게 되서 부하가 커집니다. Transaction이라는 기능이 사실 또 그 동안 다른 쿼리의 Commit(작동 확정)을 막는 기능이어서 오래 잡고 있을 수록 DB에 부하가 심하게 쌓일 수 있거든요

아이디어를 드리면 탈퇴할 event리스트 뽑고 삭제할 이벤트 리스트뽑고 각각 deleteMany 쿼리를 쳐보시면 좋을듯. 저렇게 하면 Write 쿼리 총 3방으로 끝나는거고, 지금 쓰시는 Dynamic Transaction API 안쓰고 그냥 기존에 쓰던 배열로 넣는 트랜잭션으로도 충분할거예요.

2024-11-25 10:25 UTC, ggred0123 commented on src/club/club.repository.ts
> +      }
최대한 열심히 수정해보겠습니다! 제가 맞게 했는지 모르겠는데 그냥 deleteEvent 랑 outEvent에서 각각 이벤트데이터[]를 받아서 deletemany 하도록 수정했습니다!

2024-11-25 10:38 UTC, worjs requested changes

2024-11-25 10:38 UTC, worjs commented on src/club/club.repository.ts
> +    tx: Prisma.TransactionClient,
outEvent라는 함수 입장에서는 eventId만 잇어도 지울 수 있는데 EventData[]라는 큰 데이터가 필요한 상황이라 적절한 함수 정의가 아니라고 생각됩니다

2024-11-25 10:38 UTC, worjs commented on src/club/club.repository.ts
> +      });
<img width="988" alt="image" src="https://github.com/user-attachments/assets/f5380826-7372-46c3-b9f9-9707ad8c3d91">
Transaction API가 방식이 두가지가 있는데, Transaction 안에서 다른 서버 로직을 수행해야 하는 경우가 아니면 Sequential 방식으로 작성하는게 좋습니다. tx 이런거 안넘겨줘도 되니까 더 좋구요

2024-11-25 10:38 UTC, worjs commented on src/club/club.repository.ts
> +    const deletedEvents = await this.getShouldDeletedEvents(userId);
얘네들도 myEvents로 가져온 이벤트 데이터 리스트에서 적절하게 필터링만 하면 되지 않을까요?
배열의 filter 함수를 잘 활용해보면 좋을듯.

2024-11-25 10:38 UTC, worjs commented on src/club/club.repository.ts
> +    const deletedEvents = await this.getShouldDeletedEvents(userId);
무슨 차이냐고 물으신다면... 

복잡하지만 완벽하게 데이터를 조회하는 쿼리 2방 vs 그냥 데이터를 조금 더 가져오는 단순한 조회쿼리 1방 + 서버에서 필터링

했을 때 성능 상 뒤쪽이 압승입니다. 디비 뒷부분 수업 들으셨다면 추측 가능하실듯!

2024-11-25 11:59 UTC, ggred0123 commented on src/club/club.repository.ts
> +    tx: Prisma.TransactionClient,
그렇군요..

2024-11-25 12:01 UTC, ggred0123 commented
sequential 로 할 때 계속 오류가 나가지고 outevents와 deleteevents를 동기로 구현하여 배열을 리턴하도록 해서 transaction에서 원하는 파일 조건에 맞췄습니다. 진짜 한시간을 넘게 계속 봤네요..ㅜ

2024-11-25 12:02 UTC, ggred0123 commented
뭔가 어차피 transaction안에서 실행되니까 괜찮을 것 같아서.. 그리고 결정적으로 오류가 심하게 나서..

2024-11-25 12:02 UTC, ggred0123 commented on src/club/club.repository.ts
> +      });
구현해봤습니다!

2024-11-25 12:02 UTC, ggred0123 commented on src/club/club.repository.ts
> +    const deletedEvents = await this.getShouldDeletedEvents(userId);
확인했습니다!

2024-11-25 12:44 UTC, worjs approved these changes
고생많으셨습니다!

적당히 수정하시고 머지하셔도 될 것 같습니다.

2024-11-25 12:44 UTC, worjs commented on src/club/club.repository.ts
> +    ]);
아 deleteEvent같은 애들은 연관 테이블까지 삭제하니까 별도의 함수로 하는게 더 좋은 코드겠군요..
제대로 봤어야하는데 실수로 놓쳤군요. 같은 상황이었으면 저도 Interactive 방식으로 했을 것 같습니다.
괜히 시간 쓰게 해서 죄송합니다,,,

만약에 별도의 함수를 안만든다고 하면 prisma쿼리 5개를 배열에 직접 집어넣어서 구현할 수는 있었겠지만, 좋은 코드는 아니었을 것 같습니다.

2024-11-25 12:44 UTC, worjs commented on src/club/club.repository.ts
> +    );
어 근데 lodash 안쓰고
myEvents.filter((event -> 어쩌구)
라는 배열 함수가 있어서 그걸 말씀드린거긴해요

2024-11-25 12:48 UTC, ggred0123 commented on src/club/club.repository.ts
> +    ]);
넵 감사합니다!

2024-11-25 12:53 UTC, ggred0123 commented on src/club/club.repository.ts
> +    );
아 그렇게 수정하겠습니다!

2024-11-25 13:02 UTC, merged