클럽 삭제 api 구현( 아직 고민중..)
ggred0123/nest-study-eventory-ymkim pull request #29
Opened 2024-11-27 04:51 UTC by ggred0123

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?

이게 클럽이 삭제됨에 따라 당연히 시작하지 않은 이벤트는 삭제되는데 이미 시작된 이벤트들이 클럽 id가 삭제되면 모임이나 리뷰가 확인 가능한지 그 부분을 잘 모르겠습니다..

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-27 06:04 UTC, ggred0123 commented
여기에 올렸습니다! @worjs

2024-11-27 16:07 UTC, worjs requested changes
Club이 삭제되면, club 모임 중 이미 시작된 모임들은 지워지지 않습니다.
지워지지 않는 이유는 내가 참가했던 모임이기 때문에 기록으로서 아카이빙 되었기 때문입니다.

따라서, club이 삭제되었을 때 club 모임 중 이미 시작된 모임들은,
1.  이 모임은 수정, 삭제가 원래 불가능합니다. (이미 시작된 모임이므로) 
2. 해당 모임의 참가자들은 리뷰의 생성, 조회, 수정, 삭제가 가능합니다. (참가자이므로)
3. 이 모임과 그 리뷰들은, 클럽원이었다고 하더라도, 오로지 참가자만 조회할 수 있습니다.

위 관점에 따라 기능들을 다시 점검해보시면 좋겠습니다! 3번이 사실 상 메인인 것 같네요.

이벤트, 리뷰 조회 위주로 한번씩 검토해보시면 좋을듯!

2024-11-27 16:11 UTC, worjs commented
아, 그리고 현재까지의 구현이면 어떤 유저가 자기가 가입한 클럽이 뭐가 있는지 확인할 방법이 없는 것 같은데 맞나요?

만약 그렇다면 User 모듈에서 GET 유저 하는 API 리턴 타입에서 클럽도 리턴하도록 바꿔주면 좋을듯

2024-11-27 19:12 UTC, ggred0123 commented
오... 사실 저는 삭제괸 클럽에서 이미 시작한 이벤트라고 하더라도 클럽원들은 볼 수 있다고 생각했었는데.. 그게 아니라면 굉장히 복잡하군요..

2024-11-27 19:13 UTC, ggred0123 commented
특히 쿼리를 통해 리뷰를 조회하는 쪽이..

2024-11-27 19:34 UTC, ggred0123 commented
마지막이여서 그런지 제가 이해를 제대로 못한건지는 모르겠지만 저 3번 문제를 위한 로직을 엄청 비효율적으로 짠 것 같습니다.. 코드 분량이 좀 길 . 수있습니다..ㅠㅜㅠ 
user의 club 들 조회 같은 경우에는 event에 cityid 표기하듯이 구현했습니다.

2024-11-28 02:32 UTC, worjs requested changes
이거량 Get /events도 빠져있는거같아요
Get /reviews랑 비슷할듯?

2024-11-28 02:32 UTC, worjs commented on src/event/event.service.ts
> +    if (event?.club) {
음? `event.club` 안되나요

2024-11-28 02:32 UTC, worjs commented on src/review/review.repository.ts
> +  }
유저의 club 중 삭제된 클럽의 List을 가져오는건가요?
하지만 Delete시에 club은 soft delete하지만 clubJoin은 hard delete라서, 클럽이 삭제된 뒤에는 이걸 확인할 방법이 없지 않나요?

2024-11-28 02:32 UTC, worjs commented on src/event/event.service.ts
> +      }
clubId가 있는 event의 경우는 가장 먼저 확인해줘야하는게 해당 club의 삭제 여부가 됩니다. 
그거에 따라 흐름이 다시금 분기되기 때문입니다.
1. clubId가 있다 => user의 club join 여부 체크 (클럽 모임이니 클럽원인지 확인)
2. clubId가 삭제되었다 => user의 event join 여부 체크 (클럽이 삭제되었으니 순수하게 참가자만 조회가능)

지금 3개의 쿼리가 날아가고 있는데, 2번째를 그냥 clubid로 club 조회하는걸로 해버리고, 각 경우에 따라 1,3을 날려서 검증을 하면 충분하겠습니다

2024-11-28 02:32 UTC, worjs commented on src/review/review.service.ts
> +
filterEventReveiwInUserJoinedClub 전체에 대한 코멘트입니다.

위에서 Review 잘 조회해 왔는데, 거기에 club 관련해서 못보는거는 걸러보자! 그런 목적의 함수일겁니다.
이럴 때는 한방에 하려하면 안되고 하나씩 쉬운거부터 줄여가야 합니다.

1. clubId가 null인 것들 먼저 담습니다. 무조건 통과죠
2. clubId가 존재하는 경우를 봅니다.
    a. club의 deletedAt이 null입니다. -> 해당 클럽원인지 여부를 체크합니다.
    b. club의 deletedAt이 값입니다. -> 해당 모임 참가자인지 여부를 체크합니다.

우리는 조회에서 id로 객체를 조회하는걸 for문 돌리지 않기로 했습니다.
그럼 DB 조회를 어떻게 하면 좋을까요?

먼저 event를 한방에 가져와서 매핑해줘야 합니다. 저는 이때 clubID만 가져오지말고 아예 deletedAt까지 같이 가져올겁니다. 그리고 reviewId을 key, eventWithClub 객체를 value로 매핑합니다. 이렇게 하면 reviewId를 통해 가져온 값에 대해서 위에 나눠놓은 조건문을 추가적인 DB 조회 없이 다 따라갈 수 있게 됩니다.

그럼 그 다음 필요한건 유저 입장에서 보면 됩니다. 해당 유저가 가입한 클럽 List, 해당 유저가 참가한 모임 List.
이렇게 3방의 쿼리로 모든 조회가 잘 끝났습니다.

이제 reviewId를 조회하면서 eventWithClub을 가져오고, clubId가 null이라면 그냥 담아주고, clubId가 있다면 null인지 아닌지 여부에 따라 `해당 유저가 가입한 클럽 List`에 include인지, `해당 유저가 참가한 모임 List`에 include인지에 따라 담아주면 됩니다.

2024-11-28 02:32 UTC, worjs commented on src/review/review.service.ts
> +      }
이거는 false를 던지는거보다 InternalServerException을 던지는게 맞습니다.
방금 전에 내가 반복문 돌려서 set한건데 그게 없다면 말이 안되죠.

일어날 수 없는 일이 일어났다면 주변 코드를 잘못 건드려서 그런거라, 우리 실수라는걸 나중에 명확하게 인지하기 위해 이런 에러를 던진다고 보시면 됩니다.

2024-11-28 02:32 UTC, worjs commented on src/review/review.service.ts
> +
코드 다시 읽어보니 전체적인 접근은 맞는데, 필요없는 고려사항을 반영한 코드들이 좀 있네요!
금방 하실 수 있을 듯

2024-11-28 09:38 UTC, ggred0123 commented on src/review/review.service.ts
> +      }
넵! 확인했습니다!

2024-11-28 09:39 UTC, ggred0123 commented on src/review/review.repository.ts
> +  }
아 맞네요..

2024-11-28 09:45 UTC, ggred0123 commented on src/event/event.service.ts
> +      }
확인했습니다!

2024-11-28 12:56 UTC, worjs requested changes

2024-11-28 12:56 UTC, worjs commented on src/event/event.service.ts
>      }
이게 이렇게 하면
club이 삭제되었는데 user가 참가자더라도 조회가 안될 것 같아요
삭제된 클럽의 모임의 경우에는 참가자는 볼 수 있어야 하는데, clubJoin도 사라졌으니 저기서 다 걸려서 짤릴듯

2024-11-28 12:56 UTC, worjs commented on src/review/review.repository.ts
> +  }
음???
이거 무조건 []로 나와요!
clubJoin을 club 삭제할 때 deleteMany로 hard delete하고 있어서,
"사용자가 가입했던 삭제된 클럽"이라는 데이터 자체를 구할 수가 없습니다

2024-11-28 12:56 UTC, worjs commented on src/review/review.service.ts
> +      }
event와 동일한 코멘트!
userInClub에서 걸려서 여기까지 안올거같아요

2024-11-28 12:56 UTC, worjs commented on src/event/event.service.ts
> +      return userJoinedEvents.includes(event);
이거죠이거죠 👍👍👍

2024-11-28 12:56 UTC, worjs commented on src/review/review.service.ts
> +        deletedStartedEventIds,
getReviews 코드는 아예 다시 보시는게 좋을거같아요 ㅠㅠ
getEvents 코드는 깔끔하게 잘 해주셨습니다 그거 참고해서 다시 작성해주세요!

팁을 드리면 Map을 두개 만들 이유가 없습니다.
이미 리뷰-이벤트 맵에서 이벤트 데이터 안에 클럽ID와 deletedAt 정보가 들어있어요

2024-11-28 12:56 UTC, worjs commented on src/review/review.service.ts
> +        deletedStartedEventIds,
이전 코멘트에서 혹시 이해가 안된 부분이 있으면 다시 물어봐주시구요ㅎㅎ

2024-11-28 14:02 UTC, ggred0123 commented on src/review/review.service.ts
> +        deletedStartedEventIds,
먼저 event를 한방에 가져와서 매핑해줘야 합니다. 저는 이때 clubID만 가져오지말고 아예 deletedAt까지 같이 가져올겁니다. 그리고 reviewId을 key, eventWithClub 객체를 value로 매핑합니다. 이렇게 하면 reviewId를 통해 가져온 값에 대해서 위에 나눠놓은 조건문을 추가적인 DB 조회 없이 다 따라갈 수 있게 됩니다.

 이 부분 해석을 맵 2개를 만들라는 걸로 착각했었네요 ㅠ

2024-11-28 14:30 UTC, worjs commented on src/review/review.service.ts
> +        deletedStartedEventIds,
네네 그리고 for문 안에서 쿼리 날리는것도 수정부탁드림!

2024-11-28 14:38 UTC, ggred0123 commented on src/review/review.service.ts
> +        deletedStartedEventIds,
넵 알겠습니다!

2024-11-28 14:38 UTC, ggred0123 commented on src/event/event.service.ts
>      }
확인했습니다!

2024-11-28 15:33 UTC, worjs approved these changes
고생하셨습니다!

2024-11-28 15:34 UTC, worjs commented
> 만약 그렇다면 User 모듈에서 GET 유저 하는 API 리턴 타입에서 클럽도 리턴하도록 바꿔주면 좋을듯

진짜 찐막

2024-11-29 03:43 UTC, merged