patch 수정 기능 구현
ggred0123/nest-study-eventory-ymkim pull request #6
Opened 2024-10-31 03:12 UTC by ggred0123

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [ v] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Additional context
리뷰 수정 과정에서는 description은 null 과 undefined 를 구분할 필요가 있었는데
모임 수정 과정에서는 | null 로 정의된 것이 없어 크게 신경쓰지 않고 진행했습니다.
updatedAt이라는  response 와 request에 없는 attribute은 실제 데이터베이스의 변형에 따라 바뀌는 것을 확인하여 이 patch를 적용시켰을 때 event relation은 변하니 eventJoin의 updatedAt은 바뀌지 않는다는 것을 확인했습니다.

2024-10-31 03:44 UTC, ggred0123 commented
put기능 구현에서 payload 부분에서 patch랑 다르게 | null 이 없어서 이 부분이 request에서 모든 attribute을 쓰지 않으면 오류를 내보내야하지 않나요? patch랑 똑같이 안쓰면 그냥 쓴 부분만 업데이트 되며 정상적으로 동작하는 문제가 있습니다.ㅠㅠ

2024-10-31 13:48 UTC, worjs requested changes
오오 고생하셨습니다! 아래 코멘트 몇가지만 확인해서 올려주세요!!

2024-10-31 13:48 UTC, worjs commented on src/event/event.service.ts
> +    }
event와 eventPayload는 완전히 동일한 객체일 것 같네요.
요구사항을 지키려면 결국 이 api를 요청한 사람이 host인지를 확인해야 하는건데, 아직 그걸 확인할 방법이 없습니다. 별도로 requestUserId 이런식으로 받아오면 가능하긴 한데, 일반적인 방법은 아니고 5주차에 그거 하는 법을 알려드릴 예정이예요!

결론) host인지 검증 안해도 됨

2024-10-31 13:48 UTC, worjs commented on src/event/event.service.ts
> +    }
둘중에 하나만 있어도 충분하지 않을까요? 어떤 일이 있어도 2번째 if문 블록이 실행되지는 않을 것 같거든요!

2024-10-31 13:48 UTC, worjs commented on src/event/event.service.ts
> +    }
put이니까 payload.startTime과 payload.endTime은 항상 null/undefined가 아닌 존재하는 값일 거예요. 굳이 앞에 2개의 조건을 체크안 이유가 있나요?

2024-10-31 13:48 UTC, worjs commented on src/event/event.service.ts
> +    }
이게 사실 되게 복잡한 처리를 해줄 필요가 있어요.
payload에 startTime만 담겨져 왔다면, 기존 event 데이터에서의 endTime과의 관계를 확인해주어야 하고요,
payload에 endTime만 담겨져 왔다면, 기존 event 데이터에서의 startTime과의 관계를 확인해주어야 합니다.
둘다 담겨져 왔다면 기존 event 데이터에서의 startTime, endTime 값들은 무시하고 payload의 startTime, endTime만 고려하면 되는거죠.

2024-10-31 13:48 UTC, worjs commented on src/event/event.service.ts
> +      maxPeople: payload.maxPeople,
maxPeople은 확인없이 변경해도 되는 값일까요?

2024-10-31 13:48 UTC, worjs commented on src/event/event.service.ts
> +      cityId: payload.cityId,
얘네들도 100000같은 값을 넘겨준다면?

2024-10-31 13:48 UTC, worjs commented on src/event/payload/put-update-event.payload.ts
> +  title!: string;
얘네들은 optional하면 안될 것 같아요!

2024-10-31 13:52 UTC, worjs commented
그나저나 fork sync 문제없이 성공하셨나보네요.... 조만간 깃 고수 되실듯

2024-11-01 04:45 UTC, ggred0123 commented on src/event/event.service.ts
> +    }
넵 확인했습니다!

2024-11-01 04:46 UTC, ggred0123 commented on src/event/event.service.ts
> +    }
아 ㅎㅎ 맞네요..

2024-11-01 04:48 UTC, ggred0123 commented on src/event/event.service.ts
> +    }
patch를 먼저 구현하고 나서 똑같이 붙여넣는 과정에서.. 생각이 좀 부족 했던 것 같습니다..

2024-11-01 04:59 UTC, ggred0123 commented on src/event/payload/put-update-event.payload.ts
> +  title!: string;
넵 확인했습니다!

2024-11-01 04:59 UTC, ggred0123 commented on src/event/event.service.ts
> +      cityId: payload.cityId,
넵 확인했습니다!

2024-11-01 04:59 UTC, ggred0123 commented on src/event/event.service.ts
> +      maxPeople: payload.maxPeople,
아 맞네요..

2024-11-01 05:04 UTC, ggred0123 commented on src/event/event.service.ts
> +    }
오.. 근데 정확히 맞는 말이여서 꼭 그렇게 해줘야겠네요!

2024-11-01 05:05 UTC, ggred0123 commented
넵 백업 브랜치 생성하고 직접 보고 merge 했습니다! conflict 나는 부분이 appmodule 정도 밖에 없었던 것 같아요!

2024-11-01 05:05 UTC, ggred0123 commented
새로 pr 올리겠습니다!

2024-11-01 05:05 UTC, closed without merging