put patch 기능 구현
ggred0123/nest-study-eventory-ymkim pull request #7
Opened 2024-11-01 05:07 UTC by ggred0123

## Type
PR 종류를 확인해 주세요.
- [ v] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

2024-11-02 16:23 UTC, worjs requested changes
Patch부분 고민 많이 하셨네요!!

근데 굳이 PR 새로 안올리고 그 PR에 그대로 하셔도 될 듯 합니다(?)

2024-11-02 16:23 UTC, worjs commented on src/event/event.repository.ts
> +  }
요거 한방에 지울 수 있어요!

2024-11-02 16:23 UTC, worjs commented on src/event/event.service.ts
> +    }
이거는 이미 payload의 class-validator의 데코레이터로 처리하는 것 같은데요!

2024-11-02 16:23 UTC, worjs commented on src/event/event.service.ts
> +    }
중첩 if문은 되도록이면 하지 않는 편이 좋습니다! 코드 읽기를 어렵게하는 주범(?) 이거든요.
이 경우도 제가 보기에는 3가지 모두 한개의 if문으로 바꿀 수 있을 것 같아요.

2024-11-02 16:23 UTC, worjs commented on src/event/event.service.ts
> +    }
어라? payload에 maxPeople을 안 넣으면 에러가 나는 코드로 보입니다.

2024-11-02 16:23 UTC, worjs commented on src/event/event.service.ts
> +    }
여기에 불필요한 코드가 있는 것 같습니다~

2024-11-02 16:23 UTC, worjs commented on src/event/payload/put-update-event.payload.ts
> +  title!: string;
`@ApiProperty`!

2024-11-03 03:27 UTC, ggred0123 commented on src/event/payload/put-update-event.payload.ts
> +  title!: string;
아고 IsOptional만 없애면 되는게 아니었군요!

2024-11-03 03:28 UTC, ggred0123 commented on src/event/event.service.ts
> +    }
다 '시작된 이벤트는 수정할 수 없다'로 한번에 처리할 수 있다는 말씀이신거죠?

2024-11-03 03:28 UTC, ggred0123 commented on src/event/event.service.ts
> +    }
아고.. 그러네요..

2024-11-03 03:28 UTC, ggred0123 commented on src/event/event.service.ts
> +    }
넵 해보겠습니다!

2024-11-03 03:28 UTC, ggred0123 commented on src/event/event.service.ts
> +    }
넵 확인했습니다!

2024-11-03 03:39 UTC, ggred0123 commented on src/event/event.repository.ts
> +  }
아 orm 을 넓게 보니까 나와있네요!

2024-11-03 13:26 UTC, worjs requested changes
maxPeople 관련 코멘트만 해결하면 될 것 같습니다!

2024-11-03 13:26 UTC, worjs commented on src/event/event.service.ts
> +    }
엇 그러니까 기존에 3가지 케이스를 if(if())로 조건을 쓰고있던걸 각각 if 하나로 바꾸면 좋겠다는 이야기였어요

2024-11-03 13:26 UTC, worjs commented on src/event/event.service.ts
> +    }
음 예를들어 사람이 이미 3명이 신청한 상태인데 최대 인원을 2명으로 변경하게되면 문제가 되지 않을까요?

2024-11-03 13:26 UTC, worjs commented on src/event/event.service.ts
> +    }
maxPeople<1은 class-validator로 처리하고 있기도 하고요

2024-11-03 14:58 UTC, ggred0123 commented on src/event/event.service.ts
> +    }
넵 확인했습니다!

2024-11-03 14:58 UTC, ggred0123 commented on src/event/event.service.ts
> +    }
확인했습니다!

2024-11-03 15:14 UTC, worjs approved these changes
LGTM! 머지하시죠

2024-11-04 04:06 UTC, ggred0123 commented
넵 감사합니다!

2024-11-04 04:06 UTC, merged